@extends('layouts.app')
@section('title',$asset->alt_text?:'Uploaded 3D model')
@push('styles')<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js"}}</script>@endpush
@section('content')
<section class="wrap" style="padding:32px"><h1>{{ $asset->alt_text?:$asset->original_name }}</h1><p>Uploaded {{ strtoupper($format) }} · drag to orbit and scroll to zoom.</p><div id="model-host" style="height:65vh;min-height:350px;background:#17191b;border-radius:20px;position:relative" data-model-url="{{ $modelUrl }}" data-model-format="{{ $format }}">
@if(in_array($format,['glb','gltf']))<model-viewer src="{{ $modelUrl }}" camera-controls auto-rotate shadow-intensity="1" style="width:100%;height:100%" aria-label="Uploaded 3D model"></model-viewer>@endif
</div><p id="model-state" role="status">Loading verified uploaded model…</p><a href="{{ $modelUrl }}">Download original model</a></section>
@endsection
@push('styles')<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/"}}</script>@endpush
@push('scripts')
@if(in_array($format,['glb','gltf']))<script type="module" src="https://cdn.jsdelivr.net/npm/@google/model-viewer@4.0.0/dist/model-viewer.min.js"></script><script>const m=document.querySelector('model-viewer');m.addEventListener('load',()=>document.getElementById('model-state').textContent='Uploaded model loaded.');m.addEventListener('error',()=>document.getElementById('model-state').textContent='Model viewer could not decode this file. Download the original or replace it in admin.');</script>
@else
<script type="module">const host=document.getElementById('model-host'),state=document.getElementById('model-state');try{if(host.dataset.modelFormat==='splat'){const gs=await import('https://cdn.jsdelivr.net/npm/@mkkellogg/gaussian-splats-3d@0.4.7/build/gaussian-splats-3d.module.js');const viewer=new gs.Viewer({rootElement:host,sharedMemoryForWorkers:false});await viewer.addSplatScene(host.dataset.modelUrl);viewer.start();state.textContent='Uploaded splat loaded.';}else{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js');const {PLYLoader}=await import('https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/loaders/PLYLoader.js');const {OrbitControls}=await import('https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/controls/OrbitControls.js');const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(host.clientWidth,host.clientHeight);host.append(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(50,host.clientWidth/host.clientHeight,.01,10000),controls=new OrbitControls(camera,renderer.domElement);const g=await new PLYLoader().loadAsync(host.dataset.modelUrl);g.computeBoundingSphere();const radius=g.boundingSphere.radius;g.center();scene.add(new THREE.Points(g,new THREE.PointsMaterial({size:radius/180,vertexColors:!!g.attributes.color,color:0xdddddd})));camera.position.set(0,0,radius*3);controls.update();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});state.textContent='Uploaded point cloud loaded.';}}catch(e){state.textContent='Viewer could not load this model: '+e.message;}</script>
@endif
@endpush
