<?php
namespace Tests\Feature;
use App\Models\{User,Record,MediaAsset};
use Database\Seeders\ReferenceContentSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;
class ExperienceSystemTest extends TestCase {
 use RefreshDatabase;
 private function admin():User{return User::factory()->create(['is_admin'=>true]);}
 private function record(string $type='venues',string $status='draft'):Record{return Record::create(['type'=>$type,'slug'=>'qa-'.bin2hex(random_bytes(4)),'name'=>'QA experience','description'=>'Original description','status'=>$status,'payload'=>[]]);}
 public function test_fresh_home_and_all_directory_types_render():void{$this->get('/')->assertOk();foreach(array_keys(config('kicc.types')) as $type)$this->get('/'.$type)->assertOk();$this->get('/national-government')->assertOk();}
 public function test_authentication_and_admin_authorization_are_server_enforced():void{$this->get('/admin')->assertRedirect('/login');$this->actingAs(User::factory()->create())->get('/admin')->assertForbidden();$this->actingAs($this->admin())->get('/admin')->assertOk();}
 public function test_login_rejects_invalid_credentials_and_accepts_real_account():void{$u=User::factory()->create(['password'=>'VerifiedTestPassword!2026','is_admin'=>true]);$this->post('/login',['email'=>$u->email,'password'=>'wrong'])->assertSessionHasErrors('email');$this->post('/login',['email'=>$u->email,'password'=>'VerifiedTestPassword!2026'])->assertRedirect('/admin');$this->assertAuthenticatedAs($u);$this->post('/logout')->assertRedirect('/');$this->assertGuest();}
 public function test_reference_import_is_idempotent_and_preserves_original_content():void{$this->seed(ReferenceContentSeeder::class);$n=Record::count();$this->seed(ReferenceContentSeeder::class);$this->assertSame($n,Record::count());$this->assertSame(47,Record::where('type','counties')->count());$this->assertSame(14,Record::where('type','products')->count());$this->assertSame(10,Record::where('type','ministries')->count());$this->assertStringContainsString('50th anniversary',Record::where('type','pages')->where('slug','about')->first()->description);$this->assertSame(0,Record::where('type','venues')->published()->count());}
 public function test_drafts_are_hidden_and_publish_unpublish_reaches_public_site():void{$r=$this->record();$this->get('/venues/'.$r->slug)->assertNotFound();$this->actingAs($this->admin())->put('/admin/records/'.$r->id,['name'=>$r->name,'slug'=>$r->slug,'status'=>'published','description'=>$r->description,'revision'=>1,'payload_json'=>'{}'])->assertRedirect();$this->get('/venues/'.$r->slug)->assertOk()->assertSee($r->name);$r->refresh();$this->put('/admin/records/'.$r->id,['name'=>$r->name,'slug'=>$r->slug,'status'=>'draft','description'=>$r->description,'revision'=>$r->revision,'payload_json'=>'{}'])->assertRedirect();$this->get('/venues/'.$r->slug)->assertNotFound();}
 public function test_create_update_delete_records_and_persist_audit():void{$this->actingAs($this->admin());$this->post('/admin/records',['type'=>'institutions','name'=>'New real institution','slug'=>'new-real-institution','status'=>'draft','description'=>'Saved institutional content','payload_json'=>'{}'])->assertRedirect();$r=Record::where('slug','new-real-institution')->firstOrFail();$this->assertDatabaseHas('audit_events',['action'=>'record.create','subject_id'=>$r->id]);$this->delete('/admin/records/'.$r->id)->assertRedirect();$this->assertDatabaseMissing('records',['id'=>$r->id]);}
 public function test_stale_revision_is_rejected():void{$r=$this->record();$r->revision=2;$r->save();$this->actingAs($this->admin())->put('/admin/records/'.$r->id,['name'=>'Stale change','slug'=>$r->slug,'status'=>'draft','revision'=>1,'payload_json'=>'{}'])->assertConflict();$this->assertSame('QA experience',$r->fresh()->name);}
 public function test_duplicate_slug_is_rejected_and_html_is_escaped():void{$r=$this->record('venues','published');$r->description='<script>alert(1)</script>';$r->save();$this->get('/venues/'.$r->slug)->assertSee('&lt;script&gt;',false)->assertDontSee('<script>alert(1)</script>',false);$this->actingAs($this->admin())->post('/admin/records',['type'=>'venues','name'=>'Duplicate','slug'=>$r->slug,'status'=>'draft','payload_json'=>'{}'])->assertSessionHasErrors('slug');}
 public function test_invalid_payload_and_negative_price_are_rejected():void{$this->actingAs($this->admin());$base=['type'=>'products','name'=>'Product','slug'=>'test-product','status'=>'draft'];$this->post('/admin/records',$base+['payload_json'=>'{"price":-1}'])->assertSessionHasErrors('payload_json');$this->post('/admin/records',$base+['payload_json'=>'{"password":"unsafe"}'])->assertSessionHasErrors('payload_json');}
 public function test_parent_cycles_are_rejected():void{$a=$this->record('institutions');$b=$this->record('institutions');$b->parent_id=$a->id;$b->save();$this->actingAs($this->admin())->put('/admin/records/'.$a->id,['name'=>$a->name,'slug'=>$a->slug,'status'=>'draft','revision'=>1,'parent_id'=>$b->id,'payload_json'=>'{}'])->assertSessionHasErrors('parent_id');}
 public function test_media_upload_publish_unpublish_and_delete_touch_storage():void{Storage::fake('local');$r=$this->record('venues','published');$this->actingAs($this->admin())->post('/admin/records/'.$r->id.'/media',['file'=>UploadedFile::fake()->image('owner-room.jpg'),'title'=>'Owner room photograph','status'=>'draft','format'=>'standard'])->assertRedirect();$m=MediaAsset::firstOrFail();Storage::disk('local')->assertExists($m->path);$this->assertDatabaseHas('audit_events',['action'=>'media.upload','subject_id'=>$m->id]);$this->delete('/admin/records/'.$r->id)->assertConflict();$this->patch('/admin/media/'.$m->id,['status'=>'published'])->assertRedirect();$this->get('/venues/'.$r->slug)->assertSee('Owner room photograph');$this->get('/media/'.$m->id)->assertOk();$this->patch('/admin/media/'.$m->id,['status'=>'draft'])->assertRedirect();$this->post('/logout');$this->get('/media/'.$m->id)->assertNotFound();$this->actingAs($this->admin())->delete('/admin/media/'.$m->id)->assertRedirect();Storage::disk('local')->assertMissing($m->path);$this->assertDatabaseMissing('media_assets',['id'=>$m->id]);}
 public function test_media_with_draft_parent_is_private_even_if_asset_is_published():void{Storage::fake('local');$r=$this->record();Storage::disk('local')->put('fixture.jpg','fixture');$m=MediaAsset::create(['record_id'=>$r->id,'disk'=>'local','path'=>'fixture.jpg','original_name'=>'fixture.jpg','mime'=>'image/jpeg','bytes'=>7,'title'=>'Private fixture','status'=>'published','format'=>'standard']);$this->get('/media/'.$m->id)->assertNotFound();}
 public function test_non_admin_cannot_upload_or_delete_media():void{$r=$this->record();$this->actingAs(User::factory()->create())->post('/admin/records/'.$r->id.'/media')->assertForbidden();}
 public function test_unsupported_file_is_rejected():void{$r=$this->record();$this->actingAs($this->admin())->post('/admin/records/'.$r->id.'/media',['file'=>UploadedFile::fake()->create('payload.php',1,'application/x-httpd-php'),'title'=>'Rejected','status'=>'draft','format'=>'standard'])->assertSessionHasErrors('file');$this->assertSame(0,MediaAsset::count());}
 public function test_enquiry_is_persisted_and_admin_can_close_it():void{$r=$this->record('venues','published');$this->post('/enquiries/'.$r->id,['name'=>'QA visitor','email'=>'visitor@example.test','message'=>'Please confirm the room availability.'])->assertRedirect();$this->assertDatabaseHas('enquiries',['record_id'=>$r->id,'status'=>'new']);$id=\App\Models\Enquiry::first()->id;$this->actingAs($this->admin())->patch('/admin/enquiries/'.$id,['status'=>'closed'])->assertRedirect();$this->assertDatabaseHas('enquiries',['id'=>$id,'status'=>'closed']);}
 public function test_every_admin_tab_and_form_renders():void{$this->actingAs($this->admin());foreach(array_keys(config('kicc.types')) as $type){$this->get('/admin/content/'.$type)->assertOk();$this->get('/admin/content/'.$type.'/create')->assertOk();}$this->get('/admin/enquiries')->assertOk();$this->get('/admin/audit')->assertOk();$this->get('/admin/records/'.$this->record()->id.'/edit')->assertOk();}
}
