<?php

/* KICC subsector pipelines — sector: agriculture (20 entries)
 * Every entry is wired to the General Ledger (LedgerService) and the
 * Mother-Pool (MotherPoolService) via the 'engine' block, and inherits
 * phase/status/regulators/tables from its parent pipeline.
 */

return [
    [
        'code' => 'B1.1',
        'parent' => 'B1',
        'sector' => 'agriculture',
        'subsector' => 'Maize & cereals lots',
        'slug' => 'maize-cereals',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["KEPHIS"],
        'tables' => ["agri_lots", "agri_lot_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B1.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B1.2',
        'parent' => 'B1',
        'sector' => 'agriculture',
        'subsector' => 'Horticulture lots',
        'slug' => 'horticulture-lots',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["KEPHIS"],
        'tables' => ["agri_lots", "agri_lot_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B1.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B1.3',
        'parent' => 'B1',
        'sector' => 'agriculture',
        'subsector' => 'Coffee & tea lots',
        'slug' => 'coffee-tea',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [4, 5]],
        'regulators' => ["KEPHIS"],
        'tables' => ["agri_lots", "agri_lot_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B1.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B1.4',
        'parent' => 'B1',
        'sector' => 'agriculture',
        'subsector' => 'Pulses & oilseeds',
        'slug' => 'pulses-oilseeds',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["KEPHIS"],
        'tables' => ["agri_lots", "agri_lot_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B1.4',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B2.1',
        'parent' => 'B2',
        'sector' => 'agriculture',
        'subsector' => 'Dairy cooperative pooling',
        'slug' => 'dairy-coops',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 5]],
        'regulators' => ["Societies Act"],
        'tables' => ["coop_pooling_batches", "coop_lot_consignments"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B2.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B2.2',
        'parent' => 'B2',
        'sector' => 'agriculture',
        'subsector' => 'Coffee union lots',
        'slug' => 'coffee-unions',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["Societies Act"],
        'tables' => ["coop_pooling_batches", "coop_lot_consignments"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B2.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B2.3',
        'parent' => 'B2',
        'sector' => 'agriculture',
        'subsector' => 'Grain cooperative pooling',
        'slug' => 'grain-coops',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 4]],
        'regulators' => ["Societies Act"],
        'tables' => ["coop_pooling_batches", "coop_lot_consignments"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B2.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B3.1',
        'parent' => 'B3',
        'sector' => 'agriculture',
        'subsector' => 'Cattle trade',
        'slug' => 'cattle',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["Veterinary certification"],
        'tables' => ["livestock_listings", "livestock_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B3.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B3.2',
        'parent' => 'B3',
        'sector' => 'agriculture',
        'subsector' => 'Sheep & goats',
        'slug' => 'sheep-goats',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["Veterinary certification"],
        'tables' => ["livestock_listings", "livestock_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B3.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B3.3',
        'parent' => 'B3',
        'sector' => 'agriculture',
        'subsector' => 'Poultry',
        'slug' => 'poultry',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["Veterinary certification"],
        'tables' => ["livestock_listings", "livestock_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B3.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B3.4',
        'parent' => 'B3',
        'sector' => 'agriculture',
        'subsector' => 'Hides & leather',
        'slug' => 'hides-leather',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [4, 5]],
        'regulators' => ["Veterinary certification"],
        'tables' => ["livestock_listings", "livestock_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B3.4',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B4.1',
        'parent' => 'B4',
        'sector' => 'agriculture',
        'subsector' => 'Lake Victoria fisheries',
        'slug' => 'lake-fisheries',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["KeFS/Coast gov"],
        'tables' => ["fisheries_catches", "fisheries_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B4.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B4.2',
        'parent' => 'B4',
        'sector' => 'agriculture',
        'subsector' => 'Coastal marine fisheries',
        'slug' => 'marine-fisheries',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["KeFS/Coast gov"],
        'tables' => ["fisheries_catches", "fisheries_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B4.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B4.3',
        'parent' => 'B4',
        'sector' => 'agriculture',
        'subsector' => 'Aquaculture',
        'slug' => 'aquaculture',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => ["KeFS/Coast gov"],
        'tables' => ["fisheries_catches", "fisheries_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B4.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B5.1',
        'parent' => 'B5',
        'sector' => 'agriculture',
        'subsector' => 'Vegetables — EU desks',
        'slug' => 'vegetables-eu',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => ["KEPHIS", "Plant protection conventions"],
        'tables' => ["hort_export_permits", "hort_compliance_documents"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B5.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B5.2',
        'parent' => 'B5',
        'sector' => 'agriculture',
        'subsector' => 'Fruits — Middle East desks',
        'slug' => 'fruits-middle-east',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => ["KEPHIS", "Plant protection conventions"],
        'tables' => ["hort_export_permits", "hort_compliance_documents"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B5.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B5.3',
        'parent' => 'B5',
        'sector' => 'agriculture',
        'subsector' => 'Cut flowers',
        'slug' => 'flowers',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => ["KEPHIS", "Plant protection conventions"],
        'tables' => ["hort_export_permits", "hort_compliance_documents"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B5.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B6.1',
        'parent' => 'B6',
        'sector' => 'agriculture',
        'subsector' => 'Fertilizer advances',
        'slug' => 'fertilizer-credit',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_financing_advances", "input_financing_repayments"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B6.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B6.2',
        'parent' => 'B6',
        'sector' => 'agriculture',
        'subsector' => 'Certified seed advances',
        'slug' => 'seed-credit',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_financing_advances", "input_financing_repayments"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B6.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'B6.3',
        'parent' => 'B6',
        'sector' => 'agriculture',
        'subsector' => 'Small equipment advances',
        'slug' => 'equipment-credit',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_financing_advances", "input_financing_repayments"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'B6.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
];
