<?php

/* KICC subsector pipelines — sector: financing (12 entries)
 * Every entry is wired to the General Ledger (LedgerService) and the
 * Mother-Pool (MotherPoolService) via the 'engine' block, and inherits
 * phase/status/regulators/tables from its parent pipeline.
 */

return [
    [
        'code' => 'F1.1',
        'parent' => 'F1',
        'sector' => 'financing',
        'subsector' => 'SME lending',
        'slug' => 'sme-lending',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["financing_facilities", "financing_disbursements"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F1.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F1.2',
        'parent' => 'F1',
        'sector' => 'financing',
        'subsector' => 'Trade treasury',
        'slug' => 'trade-treasury',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["financing_facilities", "financing_disbursements"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F1.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F1.3',
        'parent' => 'F1',
        'sector' => 'financing',
        'subsector' => 'Treasury float yield',
        'slug' => 'float-yield',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["financing_facilities", "financing_disbursements"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F1.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F2.1',
        'parent' => 'F2',
        'sector' => 'financing',
        'subsector' => 'PO-backed advances',
        'slug' => 'po-financing',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["invoice_financing_requests", "invoice_financing_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F2.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F2.2',
        'parent' => 'F2',
        'sector' => 'financing',
        'subsector' => 'Invoice discounting',
        'slug' => 'invoice-discounting',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "2-3%/month, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["invoice_financing_requests", "invoice_financing_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F2.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F3.1',
        'parent' => 'F3',
        'sector' => 'financing',
        'subsector' => 'Season input advances',
        'slug' => 'input-advance',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "harvest recovery, CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_advance_requests", "input_advance_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F3.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F3.2',
        'parent' => 'F3',
        'sector' => 'financing',
        'subsector' => 'Harvest repayment rails',
        'slug' => 'harvest-repay',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "CBK-gated"],
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_advance_requests", "input_advance_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F3.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F4.1',
        'parent' => 'F4',
        'sector' => 'financing',
        'subsector' => 'Embedded insurance',
        'slug' => 'embedded-insurance',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [10, 20]],
        'regulators' => ["IRA intermediary"],
        'tables' => ["embedded_insurance_policies", "kyb_checks"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F4.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F4.2',
        'parent' => 'F4',
        'sector' => 'financing',
        'subsector' => 'KYB API checks',
        'slug' => 'kyb-api',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => ["IRA intermediary"],
        'tables' => ["embedded_insurance_policies", "kyb_checks"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F4.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F4.3',
        'parent' => 'F4',
        'sector' => 'financing',
        'subsector' => 'Device & asset insurance',
        'slug' => 'device-insurance',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [10, 20]],
        'regulators' => ["IRA intermediary"],
        'tables' => ["embedded_insurance_policies", "kyb_checks"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F4.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F5.1',
        'parent' => 'F5',
        'sector' => 'financing',
        'subsector' => 'Escrow float',
        'slug' => 'escrow-float',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "KES 0 until CBK confirms"],
        'regulators' => ["CBK ruling REQUIRED"],
        'tables' => ["escrow_float_accounts", "escrow_float_yields"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F5.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'F5.2',
        'parent' => 'F5',
        'sector' => 'financing',
        'subsector' => 'Treasury parking',
        'slug' => 'treasury-parking',
        'phase' => '3',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "CBK-gated"],
        'regulators' => ["CBK ruling REQUIRED"],
        'tables' => ["escrow_float_accounts", "escrow_float_yields"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'F5.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
];
