<?php

/* KICC subsector pipelines — sector: government (14 entries)
 * Every entry is wired to the General Ledger (LedgerService) and the
 * Mother-Pool (MotherPoolService) via the 'engine' block, and inherits
 * phase/status/regulators/tables from its parent pipeline.
 */

return [
    [
        'code' => 'G1.1',
        'parent' => 'G1',
        'sector' => 'government',
        'subsector' => 'Business permits',
        'slug' => 'business-permits',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1.5, 2]],
        'regulators' => ["County assembly approvals"],
        'tables' => ["county_revenue_heads", "county_revenue_collections"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G1.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G1.2',
        'parent' => 'G1',
        'sector' => 'government',
        'subsector' => 'Parking fees',
        'slug' => 'parking-fees',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1.5, 2]],
        'regulators' => ["County assembly approvals"],
        'tables' => ["county_revenue_heads", "county_revenue_collections"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G1.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G1.3',
        'parent' => 'G1',
        'sector' => 'government',
        'subsector' => 'Market fees',
        'slug' => 'market-fees',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1.5, 2]],
        'regulators' => ["County assembly approvals"],
        'tables' => ["county_revenue_heads", "county_revenue_collections"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G1.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G1.4',
        'parent' => 'G1',
        'sector' => 'government',
        'subsector' => 'Land rates',
        'slug' => 'land-rates',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1.5, 2]],
        'regulators' => ["County assembly approvals"],
        'tables' => ["county_revenue_heads", "county_revenue_collections"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G1.4',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G2.1',
        'parent' => 'G2',
        'sector' => 'government',
        'subsector' => 'County tenders escrow',
        'slug' => 'county-tenders',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [0.5, 1]],
        'regulators' => ["IFMIS integration REQUIRED"],
        'tables' => ["county_procurement_pos", "county_procurement_escrows"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G2.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G2.2',
        'parent' => 'G2',
        'sector' => 'government',
        'subsector' => 'County supplies escrow',
        'slug' => 'county-supplies',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [0.5, 1]],
        'regulators' => ["IFMIS integration REQUIRED"],
        'tables' => ["county_procurement_pos", "county_procurement_escrows"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G2.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'H1.1',
        'parent' => 'H1',
        'sector' => 'government',
        'subsector' => 'National tenders escrow',
        'slug' => 'national-tenders',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [0.5, 1]],
        'regulators' => ["IFMIS/NT integration REQUIRED"],
        'tables' => ["national_procurement_tenders", "national_procurement_escrows"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'H1.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'H1.2',
        'parent' => 'H1',
        'sector' => 'government',
        'subsector' => 'Ministry supply escrow',
        'slug' => 'ministry-supply',
        'phase' => '3',
        'status' => 'licence_gated',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [0.5, 1]],
        'regulators' => ["IFMIS/NT integration REQUIRED"],
        'tables' => ["national_procurement_tenders", "national_procurement_escrows"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'H1.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => true,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G3.1',
        'parent' => 'G3',
        'sector' => 'government',
        'subsector' => 'eCitizen-aligned services',
        'slug' => 'ecitizen-services',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "KES 50-100 convenience fee"],
        'regulators' => ["eCitizen alignment"],
        'tables' => ["egov_service_catalog", "egov_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G3.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G3.2',
        'parent' => 'G3',
        'sector' => 'government',
        'subsector' => 'County e-services',
        'slug' => 'county-eservices',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "KES 50-100 convenience fee"],
        'regulators' => ["eCitizen alignment"],
        'tables' => ["egov_service_catalog", "egov_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G3.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G3.3',
        'parent' => 'G3',
        'sector' => 'government',
        'subsector' => 'Licensing facilitation',
        'slug' => 'licensing',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "KES 50-100 convenience fee"],
        'regulators' => ["eCitizen alignment"],
        'tables' => ["egov_service_catalog", "egov_transactions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G3.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G4.1',
        'parent' => 'G4',
        'sector' => 'government',
        'subsector' => 'Market reports',
        'slug' => 'market-reports',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "subscription"],
        'regulators' => ["ODPC"],
        'tables' => ["data_products", "data_product_subscriptions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G4.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G4.2',
        'parent' => 'G4',
        'sector' => 'government',
        'subsector' => 'County price indices',
        'slug' => 'price-indices',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "subscription"],
        'regulators' => ["ODPC"],
        'tables' => ["data_products", "data_product_subscriptions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G4.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'G4.3',
        'parent' => 'G4',
        'sector' => 'government',
        'subsector' => 'Data API access',
        'slug' => 'api-access',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "subscription/API"],
        'regulators' => ["ODPC"],
        'tables' => ["data_products", "data_product_subscriptions"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'G4.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
];
