<?php

/* KICC subsector pipelines — sector: tourism (15 entries)
 * Every entry is wired to the General Ledger (LedgerService) and the
 * Mother-Pool (MotherPoolService) via the 'engine' block, and inherits
 * phase/status/regulators/tables from its parent pipeline.
 */

return [
    [
        'code' => 'C1.1',
        'parent' => 'C1',
        'sector' => 'tourism',
        'subsector' => 'Attractions & parks',
        'slug' => 'attractions',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [15, 18]],
        'regulators' => ["TRA-adjacent"],
        'tables' => ["experience_bookings", "experience_availability"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C1.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C1.2',
        'parent' => 'C1',
        'sector' => 'tourism',
        'subsector' => 'Activities & experiences',
        'slug' => 'activities',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [15, 18]],
        'regulators' => ["TRA-adjacent"],
        'tables' => ["experience_bookings", "experience_availability"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C1.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C1.3',
        'parent' => 'C1',
        'sector' => 'tourism',
        'subsector' => 'Day tours',
        'slug' => 'day-tours',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [15, 18]],
        'regulators' => ["TRA-adjacent"],
        'tables' => ["experience_bookings", "experience_availability"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C1.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C2.1',
        'parent' => 'C2',
        'sector' => 'tourism',
        'subsector' => 'Leisure itineraries',
        'slug' => 'leisure-travel',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => [],
        'tables' => ["trip_itineraries", "trip_itinerary_items"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C2.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C2.2',
        'parent' => 'C2',
        'sector' => 'tourism',
        'subsector' => 'Business travel itineraries',
        'slug' => 'business-travel',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => [],
        'tables' => ["trip_itineraries", "trip_itinerary_items"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C2.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C2.3',
        'parent' => 'C2',
        'sector' => 'tourism',
        'subsector' => 'MICE travel itineraries',
        'slug' => 'mice-travel',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => [],
        'tables' => ["trip_itineraries", "trip_itinerary_items"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C2.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C3.1',
        'parent' => 'C3',
        'sector' => 'tourism',
        'subsector' => 'Safari packages (MoR)',
        'slug' => 'safari-packages',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [20, 30]],
        'regulators' => ["IATA/TALA", "ODPC"],
        'tables' => ["tour_packages", "tour_package_bookings"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C3.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C3.2',
        'parent' => 'C3',
        'sector' => 'tourism',
        'subsector' => 'Coast beach packages (MoR)',
        'slug' => 'beach-packages',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [20, 30]],
        'regulators' => ["IATA/TALA", "ODPC"],
        'tables' => ["tour_packages", "tour_package_bookings"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C3.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C3.3',
        'parent' => 'C3',
        'sector' => 'tourism',
        'subsector' => 'Flight + hotel bundles (MoR)',
        'slug' => 'flight-hotel-bundles',
        'phase' => '2',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [20, 30]],
        'regulators' => ["IATA/TALA", "ODPC"],
        'tables' => ["tour_packages", "tour_package_bookings"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C3.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C4.1',
        'parent' => 'C4',
        'sector' => 'tourism',
        'subsector' => 'County homestays',
        'slug' => 'homestays',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [13, 15]],
        'regulators' => ["County tourism"],
        'tables' => ["homestay_listings", "homestay_bookings"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C4.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C4.2',
        'parent' => 'C4',
        'sector' => 'tourism',
        'subsector' => 'Community lodges',
        'slug' => 'community-lodges',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [13, 15]],
        'regulators' => ["County tourism"],
        'tables' => ["homestay_listings", "homestay_bookings"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C4.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C4.3',
        'parent' => 'C4',
        'sector' => 'tourism',
        'subsector' => 'Cultural experiences',
        'slug' => 'cultural-experiences',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [15, 20]],
        'regulators' => ["County tourism"],
        'tables' => ["homestay_listings", "homestay_bookings"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C4.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C5.1',
        'parent' => 'C5',
        'sector' => 'tourism',
        'subsector' => 'Conference venues',
        'slug' => 'conference-venues',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "booking fee + dynamic pricing"],
        'regulators' => [],
        'tables' => ["venue_listings", "venue_bookings", "booth_inventory"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C5.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C5.2',
        'parent' => 'C5',
        'sector' => 'tourism',
        'subsector' => 'Exhibition booths',
        'slug' => 'exhibition-booths',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => [],
        'tables' => ["venue_listings", "venue_bookings", "booth_inventory"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C5.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'C5.3',
        'parent' => 'C5',
        'sector' => 'tourism',
        'subsector' => 'Wedding & event venues',
        'slug' => 'event-venues',
        'phase' => '1',
        'status' => 'partial',
        'economics' => ['model' => 'rate_note', 'rate_note' => "booking fee"],
        'regulators' => [],
        'tables' => ["venue_listings", "venue_bookings", "booth_inventory"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'C5.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
];
