<?php

/* KICC subsector pipelines — sector: trade (22 entries)
 * Every entry is wired to the General Ledger (LedgerService) and the
 * Mother-Pool (MotherPoolService) via the 'engine' block, and inherits
 * phase/status/regulators/tables from its parent pipeline.
 */

return [
    [
        'code' => 'A1.1',
        'parent' => 'A1',
        'sector' => 'trade',
        'subsector' => 'General merchandise',
        'slug' => 'general-merchandise',
        'phase' => '1',
        'status' => 'built',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 5]],
        'regulators' => [],
        'tables' => ["products", "orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A1.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A1.2',
        'parent' => 'A1',
        'sector' => 'trade',
        'subsector' => 'Electronics & phones',
        'slug' => 'electronics',
        'phase' => '1',
        'status' => 'built',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => [],
        'tables' => ["products", "orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A1.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A1.3',
        'parent' => 'A1',
        'sector' => 'trade',
        'subsector' => 'Fashion & apparel',
        'slug' => 'fashion',
        'phase' => '1',
        'status' => 'built',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [4, 5]],
        'regulators' => [],
        'tables' => ["products", "orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A1.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A1.4',
        'parent' => 'A1',
        'sector' => 'trade',
        'subsector' => 'Home & garden',
        'slug' => 'home-garden',
        'phase' => '1',
        'status' => 'built',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 5]],
        'regulators' => [],
        'tables' => ["products", "orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A1.4',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A1.5',
        'parent' => 'A1',
        'sector' => 'trade',
        'subsector' => 'B2B industrial supplies',
        'slug' => 'b2b-industrial',
        'phase' => '1',
        'status' => 'built',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 4]],
        'regulators' => [],
        'tables' => ["products", "orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A1.5',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A1.6',
        'parent' => 'A1',
        'sector' => 'trade',
        'subsector' => 'Exhibitor subscriptions & ads',
        'slug' => 'exhibitor-ads',
        'phase' => '1',
        'status' => 'built',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => [],
        'tables' => ["products", "orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A1.6',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A2.1',
        'parent' => 'A2',
        'sector' => 'trade',
        'subsector' => 'Sea freight consolidation',
        'slug' => 'sea-freight',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "landed-cost margin + FX spread"],
        'regulators' => [],
        'tables' => ["logistics_shipments", "logistics_carrier_quotes"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A2.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A2.2',
        'parent' => 'A2',
        'sector' => 'trade',
        'subsector' => 'Air freight express',
        'slug' => 'air-freight',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "landed-cost margin + FX spread"],
        'regulators' => [],
        'tables' => ["logistics_shipments", "logistics_carrier_quotes"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A2.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A2.3',
        'parent' => 'A2',
        'sector' => 'trade',
        'subsector' => 'Northern & EAC road corridors',
        'slug' => 'road-corridor',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'rate_note', 'rate_note' => "landed-cost margin"],
        'regulators' => [],
        'tables' => ["logistics_shipments", "logistics_carrier_quotes"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A2.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A2.4',
        'parent' => 'A2',
        'sector' => 'trade',
        'subsector' => 'Customs brokerage desk',
        'slug' => 'customs-brokerage',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'flat_fee', 'flat_fee_kes' => 0],
        'regulators' => [],
        'tables' => ["logistics_shipments", "logistics_carrier_quotes"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A2.4',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A3.1',
        'parent' => 'A3',
        'sector' => 'trade',
        'subsector' => 'Cement & steel',
        'slug' => 'cement-steel',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 4]],
        'regulators' => [],
        'tables' => ["groupbuy_campaigns", "groupbuy_orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A3.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A3.2',
        'parent' => 'A3',
        'sector' => 'trade',
        'subsector' => 'Roofing & iron sheets',
        'slug' => 'roofing',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 4]],
        'regulators' => [],
        'tables' => ["groupbuy_campaigns", "groupbuy_orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A3.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A3.3',
        'parent' => 'A3',
        'sector' => 'trade',
        'subsector' => 'Finishes & fittings',
        'slug' => 'finishes',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [3, 4]],
        'regulators' => [],
        'tables' => ["groupbuy_campaigns", "groupbuy_orders"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A3.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A4.1',
        'parent' => 'A4',
        'sector' => 'trade',
        'subsector' => 'County market-day stalls',
        'slug' => 'county-market-day',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 3]],
        'regulators' => ["County finance acts"],
        'tables' => ["county_wholesale_listings", "market_day_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A4.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A4.2',
        'parent' => 'A4',
        'sector' => 'trade',
        'subsector' => 'Bulk wholesale trade',
        'slug' => 'bulk-wholesale',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 2]],
        'regulators' => ["County finance acts"],
        'tables' => ["county_wholesale_listings", "market_day_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A4.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A4.3',
        'parent' => 'A4',
        'sector' => 'trade',
        'subsector' => 'Agrovet supply',
        'slug' => 'agrovet-supply',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 3]],
        'regulators' => ["County finance acts"],
        'tables' => ["county_wholesale_listings", "market_day_sales"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A4.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A5.1',
        'parent' => 'A5',
        'sector' => 'trade',
        'subsector' => 'Food & beverage franchises',
        'slug' => 'food-franchise',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 3]],
        'regulators' => [],
        'tables' => ["franchise_listings", "franchise_matches"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A5.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A5.2',
        'parent' => 'A5',
        'sector' => 'trade',
        'subsector' => 'Retail franchises',
        'slug' => 'retail-franchise',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 3]],
        'regulators' => [],
        'tables' => ["franchise_listings", "franchise_matches"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A5.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A5.3',
        'parent' => 'A5',
        'sector' => 'trade',
        'subsector' => 'Auto dealerships',
        'slug' => 'auto-dealership',
        'phase' => '1',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [2, 3]],
        'regulators' => [],
        'tables' => ["franchise_listings", "franchise_matches"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A5.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A6.1',
        'parent' => 'A6',
        'sector' => 'trade',
        'subsector' => 'Retail business sales',
        'slug' => 'retail-businesses',
        'phase' => '3',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 2]],
        'regulators' => [],
        'tables' => ["sme_business_listings", "sme_acquisition_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A6.1',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A6.2',
        'parent' => 'A6',
        'sector' => 'trade',
        'subsector' => 'Service business sales',
        'slug' => 'service-businesses',
        'phase' => '3',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 2]],
        'regulators' => [],
        'tables' => ["sme_business_listings", "sme_acquisition_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A6.2',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
    [
        'code' => 'A6.3',
        'parent' => 'A6',
        'sector' => 'trade',
        'subsector' => 'Manufacturing SME sales',
        'slug' => 'manufacturing-smes',
        'phase' => '3',
        'status' => 'absent',
        'economics' => ['model' => 'commission', 'take_rate_pct' => [1, 2]],
        'regulators' => [],
        'tables' => ["sme_business_listings", "sme_acquisition_deals"],
        'kill_criteria' => ['max_dispute_rate_pct' => 3.0, 'min_fill_rate_pct' => 70.0, 'consecutive_months' => 2],
        'engine' => [
            'ledger' => [
                'service' => 'App\\Kicc\\Services\\LedgerService',
                'pipeline_code' => 'A6.3',
                'hold_account' => 'escrow_clearing',
                'payable_account' => 'merchant_payable',
                'fee_credit_account' => 'fees_income',
                'lifecycle' => ['hold', 'capture', 'split', 'release', 'refund'],
                'earning_locked' => false,
            ],
            'mother_pool' => [
                'service' => 'App\\Kicc\\Services\\MotherPoolService',
                'event' => 'contribution.recorded',
                'holdback_rate' => 0.10,
                'equalisation_rate' => 0.005,
                'quality_service' => 'App\\Kicc\\Services\\QualityScoreService',
            ],
        ],
    ],
];
