[kicc-experience]
user = www-data
group = www-data
listen = /run/php/kicc-experience.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm = ondemand
pm.max_children = 12
pm.process_idle_timeout = 15s
pm.max_requests = 400
clear_env = yes
security.limit_extensions = .php
php_admin_value[upload_max_filesize] = 200M
php_admin_value[post_max_size] = 210M
php_admin_value[memory_limit] = 256M
php_admin_value[max_execution_time] = 180
php_admin_value[display_errors] = Off
catch_workers_output = yes
