@extends('layouts.nexora')
@section('title', $product->name.' · Edit product')
@section('content')
<section class="as-card"><span class="as-eyebrow">{{ $institution->county?->name }} → {{ $institution->name }} → Products → Edit</span><h1>{{ $product->name }}</h1><p>Product ID {{ $product->id }} · Institution ID {{ $institution->id }}</p><a class="as-cta" href="{{ route('institution.products.index',$institution->slug) }}">Back to institution products</a></section>
@if(session('success'))<div class="as-card" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="as-card" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<section class="as-card"><h2>Product details</h2><form method="POST" enctype="multipart/form-data" action="{{ route('institution.products.save',[$institution->slug,$product->id]) }}">@csrf<div class="up-grid"><label>Name<input name="name" value="{{ $product->name }}" required></label><label>Price<input name="price" type="number" min="0" step="0.01" value="{{ $product->price??0 }}" required></label><label>Stock<input name="stock" type="number" min="0" value="{{ $product->variants->first()?->stock??0 }}" required></label><label>Unit<input name="unit" value="{{ $product->unit }}"></label><label>Description<textarea name="description">{{ $product->description }}</textarea></label></div><button class="as-cta" type="submit">Save product details</button></form></section>
<section class="as-card" data-product-upload data-base="{{ route('admin.uploads') }}" data-owner-type="{{ \App\Models\Marketplace\Product::class }}" data-owner-id="{{ $product->id }}"><h2>Product videos · up to 2 GiB per file</h2><p>Upload directly to this product. Verified 4 MiB chunks go to R2; only a successful completion publishes the video.</p><form enctype="multipart/form-data" data-product-video-form><div class="up-grid"><label>Linked sector<select data-pv-sector required><option value="">Choose this institution's sector</option>@foreach($sectors as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>Video title<input data-pv-title required maxlength="255" value="{{ $product->name }}"></label><label>File<input data-pv-file type="file" accept="video/mp4,video/webm,video/quicktime" required></label><label>Add or replace<select data-pv-replace><option value="">Add a new product video</option>@foreach($media as $a)<option value="{{ $a->id }}">Replace {{ $a->alt_text ?: $a->original_name }}</option>@endforeach</select></label></div><button class="as-cta" data-pv-start type="submit">Upload & publish product video</button><progress data-pv-progress max="100" value="0"></progress><p data-pv-status role="status">MP4 or WebM recommended. MOV playback depends on its codec.</p><button type="button" class="as-cta" data-pv-reset hidden>Discard pending upload</button></form></section>
<section class="as-card"><h2>Published product videos</h2>@forelse($media as $a)<article><h3>{{ $a->alt_text ?: $a->original_name }}</h3><p>{{ number_format($a->size_bytes/1048576,2) }} MiB · Asset {{ $a->id }}</p><video controls muted playsinline preload="metadata" style="width:100%;max-height:350px" src="{{ url('/media/original/'.$a->path) }}"></video><form method="POST" action="{{ route('institution.products.video.delete',[$institution->slug,$product->id,$a->id]) }}" onsubmit="return confirm('Remove this video from this product?')">@csrf @method('DELETE')<button class="as-cta" type="submit">Delete this product video</button></form></article>@empty<p>No product video has been published yet.</p>@endforelse<p><a href="{{ route('marketplace.show',$product->slug) }}" target="_blank" rel="noopener noreferrer">Preview public product in a separate tab ↗</a></p></section>
@endsection
@push('scripts')<script defer src="/js/product-video-upload.js?v=product-admin-v1"></script>@endpush
