@extends('layouts.nexora')
@section('title', $product->name.' · Edit product')
@section('content')
<section class="as-card"><span class="as-eyebrow">{{ $institution->county?->name }} → {{ $institution->name }} → Products → Edit</span><h1>{{ $product->name }}</h1><p>Product ID {{ $product->id }} · Institution ID {{ $institution->id }}</p><a class="as-cta" href="{{ route('institution.products.index',$institution->slug) }}">Back to institution products</a></section>
@if(session('success'))<div class="as-card" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="as-card" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<section class="as-card"><h2>Offering details</h2><form method="POST" enctype="multipart/form-data" action="{{ route('institution.products.save',[$institution->slug,$product->id]) }}">@csrf@include('experience.admin.offering-fields')<button class="as-cta" type="submit">Save offering & sync</button></form></section>
<section class="as-card"><h2>Offers & packages</h2>@forelse($product->offers as $offer)<article><h3>{{ $offer->title }}</h3><p>{{ $offer->terms }}</p><p>{{ $offer->is_published?'Published within date window':'Draft · needs review' }} @if($offer->ends_at)· Ends {{ $offer->ends_at->toDateString() }}@endif</p><form method="POST" action="{{ route('institution.offers.delete',[$institution->slug,$product->id,$offer->id]) }}">@csrf @method('DELETE')<button class="as-cta">Remove offer</button></form></article>@empty<p>No offers for this offering.</p>@endforelse
<details><summary>Add an offer</summary><form method="POST" action="{{ route('institution.offers.store',[$institution->slug,$product->id]) }}">@csrf<div class="up-grid"><label>Offer title<input name="title" required></label><label>Terms / inclusions<textarea name="terms" required></textarea></label><label>Offer price (optional)<input type="number" name="price" min="0" step="0.01"></label><label>Source URL<input type="url" name="source_url"></label><label>Starts<input type="datetime-local" name="starts_at"></label><label>Ends<input type="datetime-local" name="ends_at"></label><label><input type="checkbox" name="is_published" value="1">Publish offer</label></div><button class="as-cta">Save offer</button></form></details></section>
<section class="as-card" data-product-upload data-base="{{ route('admin.uploads') }}" data-owner-type="{{ \App\Models\Marketplace\Product::class }}" data-owner-id="{{ $product->id }}"><h2>Product videos · up to 2 GiB per file</h2><p>Non-browser codecs are converted in the background. Only ready videos appear publicly; processing failures never replace a confirmed stream with an unplayable preview.</p><p>Upload directly to this product. Verified 4 MiB chunks go to R2; only a successful completion publishes the video.</p><form enctype="multipart/form-data" data-product-video-form><div class="up-grid"><label>Linked sector<select data-pv-sector required><option value="">Choose this institution's sector</option>@foreach($sectors as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select></label><label>Video title<input data-pv-title required maxlength="255" value="{{ $product->name }}"></label><label>File<input data-pv-file type="file" accept="video/mp4,video/webm,video/quicktime" required></label><label>Add or replace<select data-pv-replace><option value="">Add a new product video</option>@foreach($media as $a)<option value="{{ $a->id }}">Replace {{ $a->alt_text ?: $a->original_name }}</option>@endforeach</select></label></div><button class="as-cta" data-pv-start type="submit">Upload & publish product video</button><progress data-pv-progress max="100" value="0"></progress><p data-pv-status role="status">MP4 or WebM recommended. MOV playback depends on its codec.</p><button type="button" class="as-cta" data-pv-reset hidden>Discard pending upload</button></form></section>
<section class="as-card"><h2>Published product videos</h2>@forelse($media as $a)<article><h3>{{ $a->alt_text ?: $a->original_name }}</h3><p>{{ number_format($a->size_bytes/1048576,2) }} MiB · Asset {{ $a->id }}</p><video controls muted playsinline preload="metadata" style="width:100%;max-height:350px" src="{{ url('/media/original/'.$a->path) }}"></video><form method="POST" action="{{ route('institution.products.video.delete',[$institution->slug,$product->id,$a->id]) }}" onsubmit="return confirm('Remove this video from this product?')">@csrf @method('DELETE')<button class="as-cta" type="submit">Delete this product video</button></form></article>@empty<p>No product video has been published yet.</p>@endforelse<p><a href="{{ route('marketplace.show',$product->slug) }}" target="_blank" rel="noopener noreferrer">Preview public product in a separate tab ↗</a></p></section>
@endsection
@push('scripts')<script defer src="/js/product-video-upload.js?v=product-admin-v1"></script>@endpush
