<?php

/* KICC pipeline registry — source of truth for economics, phases, regulators.
 * consumed by: kicc:register-pipelines, Mother-Pool reporting, activation tiers */

return [
    [
        'code' => 'A1',
        'sector' => 'trade',
        'phase' => '1',
        'status' => 'built',
        'take_rate' => '2-5% commission + subs/booths/ads',
        'regulators' => [],
        'tables' => ["products", "orders"],
        'description' => 'Domestic Marketplace (ALREADY BUILT in ann — this kit wires it into the ledger)',
    ],
    [
        'code' => 'A2',
        'sector' => 'trade',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => 'Landed-cost margin + FX spread 1-1.5% + carrier referral',
        'regulators' => [],
        'tables' => ["logistics_shipments", "logistics_carrier_quotes"],
        'description' => 'Cross-Border Logistics',
    ],
    [
        'code' => 'A3',
        'sector' => 'trade',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '2-4% commission + volume rebate share',
        'regulators' => [],
        'tables' => ["groupbuy_campaigns", "groupbuy_orders"],
        'description' => 'Construction Materials Group-Buy',
    ],
    [
        'code' => 'A4',
        'sector' => 'trade',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '1-3% commission + market-fee facilitation',
        'regulators' => ["County finance acts"],
        'tables' => ["county_wholesale_listings", "market_day_sales"],
        'description' => 'County Wholesale & Market-Day Trade',
    ],
    [
        'code' => 'A5',
        'sector' => 'trade',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '1-3% success fee per signed dealership',
        'regulators' => [],
        'tables' => ["franchise_listings", "franchise_matches"],
        'description' => 'Franchise & Dealership Matchmaking',
    ],
    [
        'code' => 'A6',
        'sector' => 'trade',
        'phase' => '3',
        'status' => 'absent',
        'take_rate' => '1-2% success fee on business transfer',
        'regulators' => [],
        'tables' => ["sme_business_listings", "sme_acquisition_deals"],
        'description' => 'SME Acquisition / Business-for-Sale',
    ],
    [
        'code' => 'B1',
        'sector' => 'agriculture',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '3-5% commission + FX spread on exports',
        'regulators' => ["KEPHIS"],
        'tables' => ["agri_lots", "agri_lot_transactions"],
        'description' => 'Agriculture Lots (grading / split payout)',
    ],
    [
        'code' => 'B2',
        'sector' => 'agriculture',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '2-5% on pooled member lots',
        'regulators' => ["Societies Act"],
        'tables' => ["coop_pooling_batches", "coop_lot_consignments"],
        'description' => 'Cooperative Rail',
    ],
    [
        'code' => 'B3',
        'sector' => 'agriculture',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '3-5% on vet-certified sales',
        'regulators' => ["Veterinary certification"],
        'tables' => ["livestock_listings", "livestock_sales"],
        'description' => 'Livestock & Leather',
    ],
    [
        'code' => 'B4',
        'sector' => 'agriculture',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '3-5% + export commission',
        'regulators' => ["KeFS/Coast gov"],
        'tables' => ["fisheries_catches", "fisheries_sales"],
        'description' => 'Fisheries & Blue Economy',
    ],
    [
        'code' => 'B5',
        'sector' => 'agriculture',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => 'Per-document fees + bank FX spread',
        'regulators' => ["KEPHIS", "Plant protection conventions"],
        'tables' => ["hort_export_permits", "hort_compliance_documents"],
        'description' => 'Horticulture Export Compliance Desk',
    ],
    [
        'code' => 'B6',
        'sector' => 'agriculture',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => '2-3%/month on input advances',
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_financing_advances", "input_financing_repayments"],
        'description' => 'Agri-Input Financing Feeder',
    ],
    [
        'code' => 'C1',
        'sector' => 'tourism',
        'phase' => '1',
        'status' => 'partial',
        'take_rate' => '15-18% OTA-style commission',
        'regulators' => ["TRA-adjacent"],
        'tables' => ["experience_bookings", "experience_availability"],
        'description' => 'Tourism & Experiences',
    ],
    [
        'code' => 'C2',
        'sector' => 'tourism',
        'phase' => '1',
        'status' => 'partial',
        'take_rate' => 'Composition layer (no direct fee)',
        'regulators' => [],
        'tables' => ["trip_itineraries", "trip_itinerary_items"],
        'description' => 'Itinerary / Trip Planning',
    ],
    [
        'code' => 'C3',
        'sector' => 'tourism',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '20-30% of total trip spend (merchant of record)',
        'regulators' => ["IATA/TALA", "ODPC"],
        'tables' => ["tour_packages", "tour_package_bookings"],
        'description' => 'Bundled Tourism (Merchant of Record)',
    ],
    [
        'code' => 'C4',
        'sector' => 'tourism',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '15% commission + curation fees',
        'regulators' => ["County tourism"],
        'tables' => ["homestay_listings", "homestay_bookings"],
        'description' => 'County Homestay & Community Tourism',
    ],
    [
        'code' => 'C5',
        'sector' => 'tourism',
        'phase' => '1',
        'status' => 'partial',
        'take_rate' => 'Booking fees + dynamic pricing + booths',
        'regulators' => [],
        'tables' => ["venue_listings", "venue_bookings", "booth_inventory"],
        'description' => 'MICE / Venue & Booths',
    ],
    [
        'code' => 'D1',
        'sector' => 'investment',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '0.1-0.5% success fee on committed capex',
        'regulators' => ["SEZA", "KenInvest"],
        'tables' => ["sez_investor_leads", "sez_deals"],
        'description' => 'Industrial / SEZ Facilitation',
    ],
    [
        'code' => 'D2',
        'sector' => 'investment',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => 'Per-hire fees + skills-tier subscriptions',
        'regulators' => [],
        'tables' => ["sez_workforce_requests", "sez_placements"],
        'description' => 'SEZ Workforce Matching',
    ],
    [
        'code' => 'D3',
        'sector' => 'investment',
        'phase' => '2',
        'status' => 'blocked',
        'take_rate' => '2-5% facilitation fee',
        'regulators' => ["Ardhisasa/MoLands partnership REQUIRED"],
        'tables' => ["real_estate_listings", "real_estate_deals"],
        'description' => 'Real Estate (title-verified)',
    ],
    [
        'code' => 'D4',
        'sector' => 'investment',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => 'FX spread + directed-investment commission',
        'regulators' => ["CBK remittance partners"],
        'tables' => ["diaspora_investment_projects", "diaspora_investments"],
        'description' => 'Diaspora Investment Corridor',
    ],
    [
        'code' => 'D5',
        'sector' => 'investment',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '2-5% trade commission + royalty split',
        'regulators' => ["Mining Act licensing"],
        'tables' => ["mining_listings", "mining_deals"],
        'description' => 'Mining Value-Chain Services',
    ],
    [
        'code' => 'F1',
        'sector' => 'financing',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => '2-3%/month + float yield',
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["financing_facilities", "financing_disbursements"],
        'description' => 'Financing & Treasury',
    ],
    [
        'code' => 'F2',
        'sector' => 'financing',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => '2-3%/month on PO-backed advances',
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["invoice_financing_requests", "invoice_financing_deals"],
        'description' => 'Supplier / Invoice Financing',
    ],
    [
        'code' => 'F3',
        'sector' => 'financing',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => 'Recovered at harvest',
        'regulators' => ["CBK licence REQUIRED"],
        'tables' => ["input_advance_requests", "input_advance_deals"],
        'description' => 'Input Financing',
    ],
    [
        'code' => 'F4',
        'sector' => 'financing',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '10-20% commission / per-check API fees',
        'regulators' => ["IRA intermediary"],
        'tables' => ["embedded_insurance_policies", "kyb_checks"],
        'description' => 'Embedded Insurance + KYB-as-a-Service',
    ],
    [
        'code' => 'F5',
        'sector' => 'financing',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => 'Interest spread (KES 0 until CBK confirms)',
        'regulators' => ["CBK ruling REQUIRED"],
        'tables' => ["escrow_float_accounts", "escrow_float_yields"],
        'description' => 'Escrow Float / Treasury Yield',
    ],
    [
        'code' => 'G1',
        'sector' => 'government',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '1.5-2% collection fee',
        'regulators' => ["County assembly approvals"],
        'tables' => ["county_revenue_heads", "county_revenue_collections"],
        'description' => 'County Own-Source Revenue Rail',
    ],
    [
        'code' => 'G2',
        'sector' => 'government',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => '0.5-1% of escrowed PO value',
        'regulators' => ["IFMIS integration REQUIRED"],
        'tables' => ["county_procurement_pos", "county_procurement_escrows"],
        'description' => 'County Procurement Rail',
    ],
    [
        'code' => 'H1',
        'sector' => 'government',
        'phase' => '3',
        'status' => 'licence_gated',
        'take_rate' => '0.5-1% of flow (largest single line)',
        'regulators' => ["IFMIS/NT integration REQUIRED"],
        'tables' => ["national_procurement_tenders", "national_procurement_escrows"],
        'description' => 'National Procurement (IFMIS-aligned)',
    ],
    [
        'code' => 'G3',
        'sector' => 'government',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => 'KES 50-100 convenience fee per transaction',
        'regulators' => ["eCitizen alignment"],
        'tables' => ["egov_service_catalog", "egov_transactions"],
        'description' => 'e-Government Services Facilitation',
    ],
    [
        'code' => 'G4',
        'sector' => 'government',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => 'Data/API subscriptions',
        'regulators' => ["ODPC"],
        'tables' => ["data_products", "data_product_subscriptions"],
        'description' => 'Market Intelligence / Data Products',
    ],
    [
        'code' => 'K1',
        'sector' => 'health',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '1.5-3% + group-purchasing fee',
        'regulators' => ["PPB/KEMSA alignment"],
        'tables' => ["health_supply_catalog", "health_supply_orders"],
        'description' => 'Health Facility Supply Marketplace',
    ],
    [
        'code' => 'K2',
        'sector' => 'health',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => 'SaaS subscriptions',
        'regulators' => ["ODPC"],
        'tables' => ["health_facility_subscriptions"],
        'description' => 'Clinic/Hospital Back-office SaaS',
    ],
    [
        'code' => 'K3',
        'sector' => 'health',
        'phase' => '2',
        'status' => 'blocked',
        'take_rate' => 'Undefined (Digital Health Act struck down)',
        'regulators' => ["Legal status unresolved"],
        'tables' => ["telehealth_sessions"],
        'description' => 'Telehealth / Health-Data layer',
    ],
    [
        'code' => 'L1',
        'sector' => 'education',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => 'Employer placement fee + cert revenue share',
        'regulators' => ["NITA/TVETA"],
        'tables' => ["skills_job_vacancies", "skills_placements"],
        'description' => 'Skills-to-Jobs (TVET)',
    ],
    [
        'code' => 'L2',
        'sector' => 'education',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => 'Per-worker verification + remittance loop',
        'regulators' => ["NEA/NITA"],
        'tables' => ["labour_migration_applications", "labour_migration_verifications"],
        'description' => 'Labour Migration Desk',
    ],
    [
        'code' => 'L3',
        'sector' => 'education',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '0.5-1% fee handling + supplies margin',
        'regulators' => ["MoE alignment"],
        'tables' => ["edu_institution_fees", "edu_fee_transactions"],
        'description' => 'Edu Commerce & Fee Rails',
    ],
    [
        'code' => 'L4',
        'sector' => 'education',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => 'Success fees',
        'regulators' => [],
        'tables' => ["attachment_opportunities", "attachment_placements"],
        'description' => 'University/Industry Attachment & IP Exchange',
    ],
    [
        'code' => 'L5',
        'sector' => 'education',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '2-4% of trade value',
        'regulators' => [],
        'tables' => ["tvet_equipment_listings", "tvet_equipment_orders"],
        'description' => 'TVET Equipment & Consumables Trade',
    ],
    [
        'code' => 'M1',
        'sector' => 'energy',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '5-10% + installer referral + insurance attach',
        'regulators' => ["EPRA alignment"],
        'tables' => ["energy_products", "energy_payg_contracts"],
        'description' => 'Clean-Energy Commerce + PAYG escrow',
    ],
    [
        'code' => 'M2',
        'sector' => 'energy',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '10-15% brokerage + verification fees',
        'regulators' => ["Carbon registries"],
        'tables' => ["carbon_projects", "carbon_credit_trades"],
        'description' => 'Carbon & Climate Assets',
    ],
    [
        'code' => 'M3',
        'sector' => 'energy',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '0.5-1% success fee on committed capex',
        'regulators' => ["WASREB/county"],
        'tables' => ["water_capex_projects", "water_project_deals"],
        'description' => 'Water Infrastructure Matchmaking',
    ],
    [
        'code' => 'M4',
        'sector' => 'energy',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => 'Trade commission',
        'regulators' => ["NEMA alignment"],
        'tables' => ["waste_listings", "waste_transactions"],
        'description' => 'Waste / Recycling Exchange',
    ],
    [
        'code' => 'N1',
        'sector' => 'mobility',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '0.5-1% collection fee + insurance/parts commissions',
        'regulators' => ["NTSA/county bylaws"],
        'tables' => ["sacco_vehicles", "sacco_daily_collections"],
        'description' => 'PSV / Matatu SACCO Operations',
    ],
    [
        'code' => 'N2',
        'sector' => 'mobility',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => '5-10% of load value',
        'regulators' => [],
        'tables' => ["freight_loads", "freight_bids"],
        'description' => 'Freight & Loads Marketplace',
    ],
    [
        'code' => 'N3',
        'sector' => 'mobility',
        'phase' => '2',
        'status' => 'absent',
        'take_rate' => '1-2% commission',
        'regulators' => ["EPRA"],
        'tables' => ["fleet_fuel_orders"],
        'description' => 'Fuel & Fleet Inputs',
    ],
    [
        'code' => 'O1',
        'sector' => 'creative',
        'phase' => '1',
        'status' => 'partial',
        'take_rate' => '10-15% commission + passes + tips',
        'regulators' => ["KFCB alignment"],
        'tables' => ["stream_sessions", "stream_passes", "stream_tips"],
        'description' => 'Creative & Livestream Economy',
    ],
    [
        'code' => 'O2',
        'sector' => 'creative',
        'phase' => '3',
        'status' => 'absent',
        'take_rate' => 'Success fees on talent deals',
        'regulators' => ["FIFA/agent licensing where relevant"],
        'tables' => ["sports_talent_profiles", "sports_deals"],
        'description' => 'Sports Talent & Events',
    ],
    [
        'code' => 'P1',
        'sector' => 'identity',
        'phase' => '1',
        'status' => 'absent',
        'take_rate' => 'Per-check API fees',
        'regulators' => ["ODPC"],
        'tables' => ["kyb_verification_requests"],
        'description' => 'KYB-as-a-Service',
    ],
];
