<?php
namespace App\Http\Controllers;
use App\Models\{Record,MediaAsset,Enquiry};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
class PublicController extends Controller {
 public function home(){return view('public.home',['counties'=>Record::published()->where('type','counties')->with('publicMedia')->orderBy('name')->get(),'venues'=>Record::published()->where('type','venues')->with('publicMedia')->orderBy('name')->limit(10)->get(),'products'=>Record::published()->where('type','products')->with('publicMedia')->orderBy('name')->limit(12)->get(),'programme'=>Record::published()->where('type','exhibitions')->with('publicMedia')->orderBy('name')->limit(6)->get(),'hero'=>Record::published()->where('type','pages')->where('slug','home')->with('publicMedia')->first()]);}
 public function directory(Request $r,string $type){abort_unless(array_key_exists($type,config('kicc.types')),404);$query=Record::published()->where('type',$type)->with('publicMedia');$q=trim((string)$r->query('q',''));if($q!=='')$query->where('name','like','%'.str_replace(['%','_'],['\\%','\\_'],$q).'%');return view('public.directory',['type'=>$type,'label'=>config('kicc.types')[$type],'records'=>$query->orderBy('name')->paginate(24)->withQueryString()]);}
 public function detail(string $type,string $slug){$record=Record::published()->where('type',$type)->where('slug',$slug)->with('publicMedia')->firstOrFail();$related=Record::published()->where('parent_id',$record->id)->with('publicMedia')->orderBy('name')->get();return view('public.detail',compact('record','related'));}
 public function national(){return view('public.national',['ministries'=>Record::published()->where('type','ministries')->with('publicMedia')->get(),'agencies'=>Record::published()->where('type','agencies')->with('publicMedia')->get(),'sectors'=>Record::published()->where('type','sectors')->get()]);}
 public function media(Request $r,MediaAsset $media){abort_unless($r->user()?->is_admin||($media->status==='published'&&$media->record?->status==='published'),404);$disk=Storage::disk($media->disk);abort_unless($disk->exists($media->path),404);if($media->disk==='local')return response()->file($disk->path($media->path),['Content-Type'=>$media->mime,'X-Content-Type-Options'=>'nosniff','Cache-Control'=>'private, no-store']);return redirect()->away($disk->temporaryUrl($media->path,now()->addSeconds(30)));}
 public function enquire(Request $r,Record $record){abort_unless($record->status==='published',404);$v=$r->validate(['name'=>'required|string|max:180','email'=>'required|email|max:240','phone'=>'nullable|string|max:60','message'=>'required|string|min:10|max:5000']);$e=Enquiry::create($v+['record_id'=>$record->id]);return back()->with('success','Your enquiry has been recorded. Reference: '.$e->id);}
}
