<?php
namespace App\Http\Controllers\Web;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\{Auth,DB,Storage,Hash};use Illuminate\Support\Str;use App\Models\User;use Aws\S3\S3Client;
class ExperienceProductionController extends Controller {
 public function __construct(){config(['app.debug'=>false]);}
 const TYPES=['counties','institutions','products','venues','exhibitions','screens','streams','content','media','media_slots','r2_objects','site_components'];
 private function reply($data,int $status=200){return response()->json($data,$status)->withHeaders(['Cache-Control'=>'private, no-store, max-age=0','CDN-Cache-Control'=>'no-store','X-KICC-Backend'=>'TiDB-R2','Set-Cookie'=>'kicc_uncached=1; Path=/experience; Secure; HttpOnly; SameSite=Lax']);}
 private function actor(){ $u=Auth::user();abort_unless($u,401,'Sign in required.');abort_if(($u->status??'active')!=='active',403,'Account is inactive.');abort_unless($u->hasAnyRole(['kicc_admin','county_admin','institution_admin']),403,'Publishing permission required.');return $u; }
 private function scope($u){if($u->hasRole('kicc_admin'))return ['type'=>'all'];if($u->hasRole('institution_admin')){$i=DB::table('county_institutions')->where('id',$u->institution_id)->first();abort_unless($i,403,'Institution assignment required.');return ['type'=>'institution','slug'=>$i->slug,'id'=>'legacy:institutions:'.$i->id];}$slug=$u->countySlug??null;$c=$slug?DB::table('counties')->where('slug',$slug)->first():DB::table('counties')->where('id',$u->county_id??$u->countyId)->first();abort_unless($c,403,'County assignment required.');return ['type'=>'county','slug'=>$c->slug,'name'=>$c->name];}
 private function permitted($u,string $type,array $p):bool {$s=$this->scope($u);if($s['type']==='all')return true;if($s['type']==='institution')return ($type==='institutions'&&($p['slug']??'')===$s['slug'])||($type==='products'&&($p['institutionId']??'')===$s['id'])||(in_array($type,['content','media'])&&($p['target']??$p['route']??'')==='/institutions/'.$s['slug']);return ($type==='counties'&&($p['slug']??'')===$s['slug'])||($type==='institutions'&&($p['county']??'')===$s['name'])||($type==='products'&&($p['c']??'')===$s['name'])||(in_array($type,['content','media'])&&($p['target']??$p['route']??'')==='/counties/'.$s['slug']);}
 private function audit($action,$type,$id,$detail=[]){DB::table('experience_audit')->insert(['actor_id'=>(string)Auth::id(),'action'=>$action,'entity_type'=>$type,'record_id'=>$id,'detail'=>json_encode($detail),'created_at'=>now()]);}
 private function record($r){return array_merge(json_decode($r->payload,true),['id'=>$r->id,'status'=>$r->status,'revision'=>$r->revision,'updatedAt'=>$r->updated_at]);}
 private function tables(bool $public,$u=null){$tables=array_fill_keys(array_merge(self::TYPES,['analytics']),[]);$mf=storage_path('app/site-component-manifest.json');$active=is_file($mf)?array_flip(array_column(json_decode(file_get_contents($mf),true)?:[],'id')):null;$q=DB::table('experience_records');if($public)$q->where('status','published');foreach($q->orderBy('created_at')->get() as $r){if($r->entity_type==='site_components'&&$active!==null&&!isset($active[$r->id]))continue;if($public&&$r->entity_type==='r2_objects')continue;$p=$this->record($r);if(!$public&&!$this->permitted($u,$r->entity_type,$p))continue;if($public){$this->redact($p);if($r->entity_type==='site_components')$p=array_intersect_key($p,array_flip(['id','key','type','value','default','variant','selector','collection','status']));} if(isset($tables[$r->entity_type]))$tables[$r->entity_type][]=$p;}return $tables;}
 private function redact(array &$p){if(isset($p['tileMedia'])&&($p['tileMedia']['state']??'')!=='published')$p['tileMedia']=['state'=>'empty'];}
 public function session(){ $u=Auth::user();return $this->reply(['csrf'=>csrf_token(),'user'=>$u?['name'=>$u->name,'email'=>$u->email,'publisher'=>$u->hasAnyRole(['kicc_admin','county_admin','institution_admin'])&&($u->status??'active')==='active']:null]); }
 public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required|string|max:255']);$u=User::where('email',$d['email'])->first();if(!$u||!Hash::check($d['password'],$u->password)||!$u->hasAnyRole(['kicc_admin','county_admin','institution_admin'])||($u->status??'active')!=='active')return $this->reply(['message'=>'Invalid publishing account credentials.'],422);if($u->mfaEnabled||$u->mfa_enabled||$u->totpSecret)return $this->reply(['message'=>'Use the existing secure login and complete MFA first.','login_url'=>'/kicc-admin/login'],409);Auth::login($u);$r->session()->regenerate();return $this->session(); }
 public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return $this->session();}
 public function publicData(){return $this->reply(['version'=>2,'tables'=>$this->tables(true),'audit'=>[]]);}
 public function adminData(){$u=$this->actor();$audit=DB::table('experience_audit')->orderByDesc('id')->limit(100);if(!$u->hasRole('kicc_admin'))$audit->where('actor_id',(string)$u->id);return $this->reply(['version'=>2,'tables'=>$this->tables(false,$u),'public_tables'=>$this->tables(true),'audit'=>$audit->get()->map(fn($a)=>['action'=>$a->action,'table'=>$a->entity_type,'id'=>$a->record_id,'time'=>$a->created_at])->all(),'scope'=>$this->scope($u)]);}
 private function validatePayload(array $p){$walk=function($v)use(&$walk){if(is_array($v)){foreach($v as $x)$walk($x);}elseif(is_string($v)){abort_if(strlen($v)>30000||str_contains($v,'<')||str_contains($v,'>'),422,'Use plain text, not HTML markup.');}};$walk($p);abort_if(strlen(json_encode($p))>150000,422,'Record is too large.');foreach(['url','image','poster','splatUrl','website','sourceUrl']as$k)if(!empty($p[$k]))abort_unless(filter_var($p[$k],FILTER_VALIDATE_URL)&&preg_match('#^https?://#',$p[$k])&&!preg_match('/[\"\x27`]/',$p[$k]),422,'Invalid HTTPS media/link URL.');if(isset($p['slug']))abort_unless(preg_match('/^[a-z0-9-]{1,190}$/',$p['slug']),422,'Invalid slug.');}
 public function save(Request $r,string $type){$u=$this->actor();abort_unless(in_array($type,self::TYPES),404);$d=$r->validate(['record'=>'required|array','record.id'=>'nullable|string|max:190','record.status'=>'required|in:draft,published','record.revision'=>'nullable|integer|min:1']);$p=$r->input('record');abort_if(in_array($type,['r2_objects','site_components']),405,'The R2 object inventory is read-only. Assign media records instead.');$this->validatePayload($p);$title=$p['name']??$p['n']??'';abort_unless(is_string($title)&&strlen(trim($title))>0&&strlen($title)<=255,422,'A title of at most 255 characters is required.');abort_unless($this->permitted($u,$type,$p),403,'This record is outside your assigned scope.');$id=$p['id']??(string)Str::uuid();$result=DB::transaction(function()use($u,$type,$p,$id){$old=DB::table('experience_records')->where('id',$id)->lockForUpdate()->first();if($old){abort_unless($old->entity_type===$type,409,'Record type mismatch.');abort_unless($this->permitted($u,$type,$this->record($old)),403);abort_unless(($p['revision']??0)===$old->revision,409,'Record changed elsewhere. Refresh before saving.');}foreach([$p['assetId']??null,$p['tileMedia']['assetId']??null]as$a)if($a){$asset=DB::table('experience_assets')->where('id',$a)->first();abort_unless($asset,422,'Uploaded asset was not found.');abort_unless($u->hasRole('kicc_admin')||$asset->actor_id===(string)$u->id,403,'Asset belongs to another publisher.');}$rev=($old->revision??0)+1;$now=now();$data=['entity_type'=>$type,'status'=>$p['status'],'payload'=>json_encode($p),'revision'=>$rev,'actor_id'=>(string)$u->id,'updated_at'=>$now];if($old)DB::table('experience_records')->where('id',$id)->update($data);else DB::table('experience_records')->insert(['id'=>$id,'created_at'=>$now]+$data);$this->audit(!$old?'create':($old->status!==$p['status']?$p['status']:'update'),$type,$id,['revision'=>$rev]);return $this->record(DB::table('experience_records')->where('id',$id)->first());});return $this->reply(['record'=>$result]);}
 public function destroy(Request $r,string $type){$u=$this->actor();abort_if(in_array($type,['r2_objects','media_slots','site_components']),405,'Keep managed slot records; hide a slot or detach its uploaded file instead.');$r->validate(['id'=>'required|string|max:190','revision'=>'required|integer']);DB::transaction(function()use($r,$u,$type){$row=DB::table('experience_records')->where('id',$r->id)->lockForUpdate()->first();abort_unless($row&&$row->entity_type===$type,404);abort_unless($this->permitted($u,$type,$this->record($row)),403);abort_unless($row->revision===$r->integer('revision'),409,'Record changed elsewhere.');DB::table('experience_records')->where('id',$r->id)->delete();$this->audit('delete',$type,$r->id);});return $this->reply(['deleted'=>true]);}
 private function disk(){return Storage::build(array_merge(config('filesystems.disks.r2'),['bucket'=>'kicc-experience-private','throw'=>true,'visibility'=>'private']));}
 private function s3(){ $c=config('filesystems.disks.r2');return new S3Client(['version'=>'latest','region'=>'auto','endpoint'=>$c['endpoint'],'use_path_style_endpoint'=>true,'credentials'=>['key'=>$c['key'],'secret'=>$c['secret']]]);}
 public function upload(Request $r){$u=$this->actor();$r->validate(['file'=>'required|file|max:51200']);$f=$r->file('file');$mime=$f->getMimeType();$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif','video/mp4'=>'mp4','video/webm'=>'webm','video/quicktime'=>'mov'];abort_unless(isset($allowed[$mime]),422,'Supported formats: JPG, PNG, WebP, GIF, MP4, WebM, MOV.');abort_if(str_starts_with($mime,'image/')&&$f->getSize()>10*1024*1024,422,'Image limit: 10 MiB.');$id=(string)Str::uuid();$path='uploads/'.$id.'.'.$allowed[$mime];$name=mb_substr(basename($f->getClientOriginalName()),0,200);$disk=$this->disk();$stream=fopen($f->getRealPath(),'rb');try{$disk->put($path,$stream,['ContentType'=>$mime]);$hash=hash_file('sha256',$f->getRealPath());DB::transaction(function()use($id,$path,$mime,$f,$u,$name,$hash){DB::table('experience_assets')->insert(['id'=>$id,'path'=>$path,'mime'=>$mime,'kind'=>str_starts_with($mime,'image/')?'image':'video','name'=>$name,'bytes'=>$f->getSize(),'sha256'=>$hash,'actor_id'=>(string)$u->id,'created_at'=>now(),'updated_at'=>now()]);$this->audit('upload','assets',$id,['bytes'=>$f->getSize(),'sha256'=>$hash]);});}catch(\Throwable $e){try{$disk->delete($path);}catch(\Throwable $x){}throw $e;}finally{if(is_resource($stream))fclose($stream);}return $this->reply(['asset'=>['id'=>$id,'url'=>url('/experience/media/'.$id),'kind'=>str_starts_with($mime,'image/')?'image':'video','bytes'=>$f->getSize()]],201);}
 private function references($id,bool $publishedOnly=false){$q=DB::table('experience_records');if($publishedOnly)$q->where('status','published');foreach($q->get()as$r){$p=$this->record($r);if($publishedOnly&&$r->entity_type==='media_slots'&&!empty($p['hidden']))continue;if(($p['assetId']??null)===$id)return true;if(($p['tileMedia']['assetId']??null)===$id&&(!$publishedOnly||($p['tileMedia']['state']??'')==='published'))return true;}return false;}
 public function deleteAsset(string $id){$u=$this->actor();$a=DB::table('experience_assets')->where('id',$id)->first();abort_unless($a,404);abort_unless($u->hasRole('kicc_admin')||$a->actor_id===(string)$u->id,403);abort_if($this->references($id),409,'Detach this asset from all records before deletion.');$disk=$this->disk();abort_unless($disk->delete($a->path)&&!$disk->exists($a->path),503,'Storage deletion was not confirmed. Retry.');DB::table('experience_assets')->where('id',$id)->delete();$this->audit('delete','assets',$id);return $this->reply(['deleted'=>true]);}
 public function serve(Request $r,string $id){$a=DB::table('experience_assets')->where('id',$id)->first();abort_unless($a,404);$u=Auth::user();$owner=$u&&($u->status??'active')==='active'&&($u->hasRole('kicc_admin')||($a->actor_id===(string)$u->id&&$u->hasAnyRole(['county_admin','institution_admin'])));abort_unless($owner||$this->references($id,true),404);$start=0;$end=(int)$a->bytes-1;$status=200;if($range=$r->header('Range')){if(!preg_match('/^bytes=(\d*)-(\d*)$/',$range,$m)||($m[1]===''&&$m[2]===''))return response('',416)->header('Content-Range','bytes */'.$a->bytes);if($m[1]==='')$start=max(0,$a->bytes-(int)$m[2]);else$start=(int)$m[1];if($m[1]!==''&&$m[2]!=='')$end=min($end,(int)$m[2]);if($start>$end||$start>=$a->bytes)return response('',416)->header('Content-Range','bytes */'.$a->bytes);$status=206;}$obj=$this->s3()->getObject(['Bucket'=>'kicc-experience-private','Key'=>$a->path,'Range'=>'bytes='.$start.'-'.$end,'@http'=>['stream'=>true,'connect_timeout'=>10,'read_timeout'=>30]]);$headers=['Content-Type'=>$a->mime,'Content-Length'=>($end-$start+1),'Accept-Ranges'=>'bytes','Cache-Control'=>'private, no-store, max-age=0','CDN-Cache-Control'=>'no-store','X-Content-Type-Options'=>'nosniff','Set-Cookie'=>'kicc_uncached=1; Path=/experience; Secure; HttpOnly; SameSite=Lax'];if($status===206)$headers['Content-Range']='bytes '.$start.'-'.$end.'/'.$a->bytes;return response()->stream(function()use($obj){$body=$obj['Body'];while(!$body->eof()){if(connection_aborted()){ $body->close();break;}echo $body->read(262144);flush();}$body->close();},$status,$headers);}
}
