<?php
namespace App\Http\Controllers\Web;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\{Auth,DB};
class MediaControlController extends Controller{
 private function actor(){ $u=Auth::user();abort_unless($u&&($u->status??'active')==='active'&&$u->hasRole('kicc_admin'),403,'KICC administrator required.');return $u;}
 private function reply($v){return response()->json($v)->withHeaders(['Cache-Control'=>'private,no-store','CDN-Cache-Control'=>'no-store','Set-Cookie'=>'kicc_uncached=1; Path=/experience; Secure; HttpOnly; SameSite=Lax']);}
 public function siteSlot(string $id){$row=DB::table('experience_records')->where('id',$id)->where('entity_type','media_slots')->where('status','published')->first();abort_unless($row,404);$p=json_decode($row->payload,true);$headers=['Cache-Control'=>'private,no-store','CDN-Cache-Control'=>'no-store','Set-Cookie'=>'kicc_uncached=1; Path=/experience; Secure; HttpOnly; SameSite=Lax'];if(!empty($p['hidden']))return response(base64_decode('R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='),200,$headers+['Content-Type'=>'image/gif']);if(!empty($p['assetId']))return redirect('/experience/media/'.$p['assetId'])->withHeaders($headers);$url=$p['url']??$p['sourceUrl']??'';abort_unless(preg_match('#^https://#',$url),404);return redirect()->away($url)->withHeaders($headers);}
 public function inventory(Request $r){$this->actor();$q=DB::table('experience_records')->where('entity_type','r2_objects');if($r->filled('search'))$q->where('payload','like','%'.$r->string('search').'%');$rows=$q->get()->map(fn($x)=>array_merge(json_decode($x->payload,true),['id'=>$x->id,'revision'=>$x->revision]));return $this->reply(['objects'=>$rows,'counts'=>['total'=>$rows->count(),'images'=>$rows->where('kind','image')->count(),'videos'=>$rows->where('kind','video')->count(),'other'=>$rows->where('kind','other')->count()]]);}
 public function functions(){ $this->actor();$path=storage_path('app/legacy-admin-functions.json');return $this->reply(['functions'=>is_file($path)?json_decode(file_get_contents($path),true):[]]);}
 public function slots(){ $this->actor();return $this->reply(['slots'=>DB::table('experience_records')->where('entity_type','media_slots')->get()->map(fn($x)=>array_merge(json_decode($x->payload,true),['id'=>$x->id,'status'=>$x->status,'revision'=>$x->revision]))]);}
 public function reconcile(){ $this->actor();$counts=[];foreach(['counties','county_institutions','products','venues','ministries','agencies','media_assets','media_derivatives','screens','exhibitions']as$t){if(\Illuminate\Support\Facades\Schema::hasTable($t))$counts[$t]=DB::table($t)->count();}return $this->reply(['legacy_database_counts'=>$counts,'publishing_counts'=>DB::table('experience_records')->select('entity_type',DB::raw('COUNT(*) count'))->groupBy('entity_type')->get(),'note'=>'Legacy commerce remains authoritative for its transaction flows; publishing records govern the new public interface.']);}
}
