<?php
namespace App\Http\Controllers\Web;
use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\{Auth,DB};use App\Support\SiteContent;
class SiteComponentsController extends Controller{
 private function actor(){ $u=Auth::user();abort_unless($u&&($u->status??'active')==='active'&&$u->hasRole('kicc_admin'),403,'KICC content administrator required.');return $u;}
 private function reply($v){return response()->json($v)->withHeaders(['Cache-Control'=>'private,no-store','CDN-Cache-Control'=>'no-store','Set-Cookie'=>'kicc_uncached=1; Path=/experience; Secure; HttpOnly; SameSite=Lax']);}
 public function index(Request $r){$this->actor();$q=DB::table('experience_records')->where('entity_type','site_components');if($r->filled('type'))$q->where('payload->type',$r->string('type')->toString());if($r->filled('search'))$q->where('payload','like','%'.$r->string('search').'%');$manifest=storage_path('app/site-component-manifest.json');$active=is_file($manifest)?array_flip(array_column(json_decode(file_get_contents($manifest),true)?:[],'id')):null;$rows=$q->get()->filter(fn($x)=>$active===null||isset($active[$x->id]))->values()->map(fn($x)=>array_merge(json_decode($x->payload,true),['id'=>$x->id,'revision'=>$x->revision,'status'=>$x->status]));return $this->reply(['components'=>$rows,'counts'=>$rows->groupBy('type')->map->count()]);}
 public function update(Request $r,string $id){return $this->save($r,$id);}
 public function save(Request $r,string $key){$u=$this->actor();$v=$r->validate(['value'=>'present','revision'=>'required|integer','status'=>'required|in:draft,published']);$result=DB::transaction(function()use($key,$v,$u){$old=DB::table('experience_records')->where('id',$key)->where('entity_type','site_components')->lockForUpdate()->first();abort_unless($old,404,'Unknown source component.');$manifest=storage_path('app/site-component-manifest.json');if(is_file($manifest))abort_unless(in_array($key,array_column(json_decode(file_get_contents($manifest),true)?:[],'id'),true),409,'This key is not bound in the current source release.');abort_unless((int)$old->revision===(int)$v['revision'],409,'Component changed elsewhere. Reload.');$p=json_decode($old->payload,true);$value=$v['value'];$type=$p['type'];if(in_array($type,['text','richtext','image','url']))abort_unless(is_string($value)&&strlen($value)<=50000,422,'Use a text value up to 50 KB.');if($type==='toggle')abort_unless(is_bool($value),422,'Visibility must be true or false.');if($type==='repeater'){abort_unless(is_array($value)&&array_is_list($value)&&count($value)<=1000,422,'Use an array of at most 1000 {id, hidden, order} rules.');foreach($value as $rule)abort_unless(is_array($rule)&&is_string($rule['id']??null)&&strlen($rule['id'])<=190&&(!isset($rule['hidden'])||is_bool($rule['hidden']))&&(!isset($rule['order'])||is_numeric($rule['order'])),422,'Each collection rule needs a record ID and optional boolean hidden/numeric order.');}if($type==='richtext')$value=SiteContent::sanitizeRich($value);if(in_array($type,['image','url'])&&$value!=='')abort_unless(preg_match('#^(https?://|/|\#|mailto:|tel:)#i',$value)&&!str_contains($value,"\n")&&!preg_match('/javascript:|data:/i',$value),422,'Only safe local, HTTP(S), mail or phone URLs are accepted.');if(($p['variant']??'')==='color')abort_unless(preg_match('/^#(?:[0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i',$value),422,'Use a valid hex colour.');$p['assetId']=null;if($type==='image'&&preg_match('#^/experience/media/([a-f0-9-]{36})$#i',$value,$am)){abort_unless(DB::table('experience_assets')->where('id',$am[1])->exists(),422,'Uploaded image asset was not found.');$p['assetId']=$am[1];}$p['value']=$value;$p['status']=$v['status'];DB::table('experience_records')->where('id',$key)->update(['payload'=>json_encode($p,JSON_UNESCAPED_UNICODE),'status'=>$v['status'],'revision'=>$old->revision+1,'actor_id'=>(string)$u->id,'updated_at'=>now()]);DB::table('experience_audit')->insert(['actor_id'=>(string)$u->id,'action'=>'edit-component','entity_type'=>'site_components','record_id'=>$key,'detail'=>json_encode(['revision'=>$old->revision+1]),'created_at'=>now()]);return ['key'=>$key,'revision'=>$old->revision+1,'value'=>$value,'status'=>$v['status']];});return $this->reply(['component'=>$result]);}
 public function reset(Request $r,string $key){$this->actor();$row=DB::table('experience_records')->where('id',$key)->where('entity_type','site_components')->first();abort_unless($row,404);$r->validate(['revision'=>'required|integer']);abort_unless((int)$row->revision===$r->integer('revision'),409,'Component changed elsewhere. Reload before reset.');$p=json_decode($row->payload,true);$r->merge(['value'=>$p['fallback']??$p['default']??null,'revision'=>$row->revision,'status'=>'published']);return $this->save($r,$key);}
 public function coverage(){ $this->actor();$manifest=storage_path('app/site-component-manifest.json');$pending=storage_path('app/site-component-pending.json');return $this->reply(['manifest'=>is_file($manifest)?json_decode(file_get_contents($manifest),true):[],'remaining'=>is_file($pending)?json_decode(file_get_contents($pending),true):[]]);}
}
