<?php
namespace App\Support;
use Illuminate\Support\Facades\{DB,Schema};
class SiteContent {
 private static ?array $values=null;
 public static function values():array {if(self::$values!==null)return self::$values;self::$values=[];try{$mf=storage_path('app/site-component-manifest.json');$active=is_file($mf)?array_flip(array_column(json_decode(file_get_contents($mf),true)?:[],'id')):null;if(Schema::hasTable('experience_records'))foreach(DB::table('experience_records')->where('entity_type','site_components')->where('status','published')->get(['id','payload'])as$r){if($active!==null&&!isset($active[$r->id]))continue;$p=json_decode($r->payload,true);self::$values[$p['key']??'']=$p;}}catch(\Throwable $e){}return self::$values;}
 public static function get(string $key,$fallback=null){$r=self::values()[$key]??null;return $r&&!($r['deleted']??false)?($r['value']??$fallback):$fallback;}
 public static function rich(string $key,string $fallback=''):string {return (string)self::get($key,$fallback);}
 public static function html(string $value):string {return preg_replace_callback('/\[\[SC:([a-z0-9-]+):([A-Za-z0-9+\/=]*)\]\]/',function($m){$r=self::values()[$m[1]]??null;$v=$r['value']??base64_decode($m[2]);return ($r['type']??'text')==='richtext'?$v:htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');},$value);}
 public static function sanitizeRich(string $html):string {$doc=new \DOMDocument();libxml_use_internal_errors(true);$doc->loadHTML('<div id="safe-content">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD|LIBXML_NONET);$allowed=['div','p','br','strong','em','b','i','u','span','a','ul','ol','li','svg','path','circle','rect','line','polyline','polygon','ellipse','g','defs','lineargradient','radialgradient','stop'];$walk=function($node)use(&$walk,$allowed){foreach(iterator_to_array($node->childNodes)as$child){if($child instanceof \DOMElement){if(!in_array(strtolower($child->tagName),$allowed)){$node->removeChild($child);continue;}foreach(iterator_to_array($child->attributes)as$a){$name=strtolower($a->name);$value=$a->value;$ok=in_array($name,['class','viewbox','xmlns','d','cx','cy','r','rx','ry','width','height','x','y','x1','x2','y1','y2','points','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','offset','stop-color','stop-opacity','aria-hidden','role','href','target','rel']);if(!$ok||str_starts_with($name,'on')||preg_match('/javascript:|data:|expression\(|url\(\s*https?:/i',$value)||($name==='href'&&!preg_match('#^(https?://|/|\#)#i',$value)))$child->removeAttribute($a->name);}if($child->tagName==='a')$child->setAttribute('rel','noopener noreferrer');}$walk($child);}};$root=$doc->getElementById('safe-content');if(!$root)return '';$walk($root);$out='';foreach($root->childNodes as$n)$out.=$doc->saveHTML($n);libxml_clear_errors();return $out;}
}
