<!doctype html>
<html lang="en" @auth data-admin-level="{{ app(\App\Services\AdminHierarchyScope::class)->level(auth()->user()) }}" @endauth><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','KICC — National Exhibition Platform')</title>
<script>(()=>{let theme;try{theme=localStorage.getItem('kicc.theme');}catch{}const requested=new URLSearchParams(location.search).get('theme');if(['light','dark'].includes(requested))theme=requested;if(!['light','dark'].includes(theme))theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;})();</script>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,200;0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=Inter+Tight:wght@300;400;450;500&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/approved-design.css?v=kicc-oct08-v7"><link rel="stylesheet" href="/css/rebuild.css?v=kicc-oct08-v7">
<link rel="stylesheet" href="/css/glass-kicc.css?v=kicc-glass-20261008d">
<link rel="stylesheet" href="/css/strict-kicc.css?v=kicc-strict-20261008e">
@stack('styles')<link rel="stylesheet" href="/css/experience-bright.css?v=experience-admin-depth-v2"><link rel="stylesheet" href="/css/experience-depth.css?v=experience-admin-depth-20261008b"><link rel="stylesheet" href="/css/reference-layout.css?v=reference-replica-v2"><link rel="stylesheet" href="/css/reference-palette.css?v=reference-replica-v2"></head>
<body class="experience-world @yield('body_class')"><a class="skip-link" href="#app">Skip to content</a>
<header class="nav rb-nav" id="nav"><div class="nav-inner"><a href="{{ route('home') }}" class="logo"><img src="{{ asset('kicclogo.png') }}" alt="KICC" class="h-5 w-auto object-contain"></a><nav class="nav-links" aria-label="Public navigation"><a href="/counties">Counties</a><a href="/marketplace">Marketplace</a><a href="/exhibitions">Exhibitions</a><a href="/venues">Venues</a><a href="/institutions">Institutions</a><a href="/national-government">National Government</a><a href="/national-sector">Sectors</a><a href="/screens">Screens</a><a href="/streams">Live</a><a href="/travel">Travel</a></nav><div class="nav-cta"><button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch to dark theme" aria-pressed="false"><span aria-hidden="true">◐</span><span data-theme-label>Dark</span></button><a class="btn ghost sm" href="{{ route('admin.portal') }}">Admin</a>@auth @if(auth()->check())<a class="btn ghost sm" href="{{ route('dashboard.index') }}">Account</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button class="btn ghost sm" type="submit">Sign out</button></form>@else<a class="btn ghost sm" href="{{ route('login') }}">Sign in</a>@endauth<button class="burger" type="button" id="burger" aria-label="Open navigation" aria-expanded="false" aria-controls="mobileMenu">☰</button></div></div></header>
<div class="mobile-menu" id="mobileMenu" hidden><button type="button" class="btn ghost" data-menu-close>Close menu</button>@foreach(['counties'=>'Counties','national-government'=>'National Government','national-sector'=>'Economic sectors','marketplace'=>'Marketplace','venues'=>'Venues','institutions'=>'Institutions','exhibitions'=>'Exhibitions','streams'=>'Live streams','screens'=>'Digital screens','travel'=>'Travel'] as $type=>$label)<a href="/{{ $type }}">{{ $label }}</a>@endforeach<a href="/national-government">National Government Portal</a><a href="{{ route('admin.portal') }}">Administration</a><a href="{{ route('login') }}">Sign in</a></div>
<main data-ui-release="reference-replica-v2" id="app" class="@yield('main-class')">@if(session('success'))<div class="wrap rb-notice" role="status">{{ session('success') }}</div>@endif @if(isset($errors) && $errors->any())<div class="wrap rb-errors" role="alert"><strong>Changes were not saved.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main>
<footer class="footer rb-footer"><div class="wrap"><a href="/" class="logo"><img src="{{ asset('kicclogo.png') }}" alt="KICC" class="h-5 w-auto object-contain"></a><p class="muted-xs" style="margin-top:25px">Africa's premier meeting venue and Kenya's national exhibition infrastructure. A national icon since 1973 — connecting all 47 counties on one video-native platform.</p><div class="rb-footer-links"><a href="/national-government">National Government Portal</a>@foreach(['counties'=>'Counties','national-government'=>'National Government','national-sector'=>'Economic sectors','marketplace'=>'Marketplace','venues'=>'Venues','institutions'=>'Institutions','exhibitions'=>'Exhibitions','streams'=>'Live streams','screens'=>'Digital screens','travel'=>'Travel'] as $type=>$label)<a href="/{{ $type }}">{{ $label }}</a>@endforeach</div><p class="muted-xs">© {{ date('Y') }} Kenyatta International Convention Centre · Kenya’s national exhibition platform.</p></div></footer>
<script defer src="/js/rebuild.js?v=experience-admin-depth-v2"></script><script defer src="/js/experience-navigation.js?v=experience-admin-depth-v2"></script><script defer src="/js/experience-depth.js?v=experience-admin-depth-20261008b"></script>@stack('scripts')</body></html>
