<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','KICC — National Exhibition Platform')</title>
<script>document.documentElement.dataset.theme='light';</script>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,200;0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=Inter+Tight:wght@300;400;450;500&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/approved-design.css?v=kicc-oct08-v7"><link rel="stylesheet" href="/css/rebuild.css?v=kicc-oct08-v7">
<link rel="stylesheet" href="/css/glass-kicc.css?v=kicc-glass-20261008d">
<link rel="stylesheet" href="/css/strict-kicc.css?v=kicc-strict-20261008e">
@stack('styles')<link rel="stylesheet" href="/css/experience-bright.css?v=experience-full-bright-v6"></head>
<body class="experience-world @yield('body_class')"><a class="skip-link" href="#app">Skip to content</a>
<header class="nav rb-nav" id="nav"><div class="nav-inner"><a href="{{ route('home') }}" class="logo"><img src="{{ asset('kicclogo.png') }}" alt="KICC" class="h-5 w-auto object-contain"></a><nav class="nav-links" aria-label="Public navigation"><a href="/counties">Counties</a><a href="/marketplace">Marketplace</a><a href="/exhibitions">Exhibitions</a><a href="/venues">Venues</a><a href="/institutions">Institutions</a><a href="/national-government">National Government</a><a href="/national-sector">Sectors</a><a href="/screens">Screens</a><a href="/streams">Live</a><a href="/travel">Travel</a><a href="/catalog">Page Atlas</a></nav><div class="nav-cta"><span class="ex-light-label">Light experience</span>@if(auth()->user()?->isAdmin())<a class="btn ghost sm" href="{{ route('experience.images.index') }}">Images</a>@endif@auth @if(auth()->check())<a class="btn ghost sm" href="{{ auth()->user()->isAdmin() ? route('kicc.admin') : route('dashboard.index') }}">Admin</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button class="btn ghost sm" type="submit">Sign out</button></form>@else<a class="btn ghost sm" href="{{ route('login') }}">Sign in</a>@endauth<button class="burger" type="button" id="burger" aria-label="Open navigation" aria-expanded="false" aria-controls="mobileMenu">☰</button></div></div></header>
<div class="mobile-menu" id="mobileMenu" hidden><button type="button" class="btn ghost" data-menu-close>Close menu</button>@foreach(['counties'=>'Counties','national-government'=>'National Government','national-sector'=>'Economic sectors','marketplace'=>'Marketplace','venues'=>'Venues','institutions'=>'Institutions','exhibitions'=>'Exhibitions','streams'=>'Live streams','screens'=>'Digital screens','travel'=>'Travel','catalog'=>'Page Atlas'] as $type=>$label)<a href="/{{ $type }}">{{ $label }}</a>@endforeach<a href="/national-government">National Government Portal</a><a href="{{ route('login') }}">Sign in</a></div>
<main data-ui-release="experience-full-bright-v6" id="app" class="@yield('main-class')">@if(session('success'))<div class="wrap rb-notice" role="status">{{ session('success') }}</div>@endif @if(isset($errors) && $errors->any())<div class="wrap rb-errors" role="alert"><strong>Changes were not saved.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main>
<footer class="footer rb-footer"><div class="wrap"><a href="/" class="logo"><img src="{{ asset('kicclogo.png') }}" alt="KICC" class="h-5 w-auto object-contain"></a><p class="muted-xs" style="margin-top:25px">Africa's premier meeting venue and Kenya's national exhibition infrastructure. A national icon since 1973 — connecting all 47 counties on one video-native platform.</p><div class="rb-footer-links"><a href="/national-government">National Government Portal</a>@foreach(['counties'=>'Counties','national-government'=>'National Government','national-sector'=>'Economic sectors','marketplace'=>'Marketplace','venues'=>'Venues','institutions'=>'Institutions','exhibitions'=>'Exhibitions','streams'=>'Live streams','screens'=>'Digital screens','travel'=>'Travel','catalog'=>'Page Atlas'] as $type=>$label)<a href="/{{ $type }}">{{ $label }}</a>@endforeach</div><p class="muted-xs">© {{ date('Y') }} Kenyatta International Convention Centre · Kenya’s national exhibition platform.</p></div></footer>
<script defer src="/js/rebuild.js?v=experience-full-bright-v6"></script><script defer src="/js/experience-navigation.js?v=experience-full-bright-v6"></script>@stack('scripts')</body></html>
