<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','KICC — National Exhibition Platform')</title>
<script>try{var t=localStorage.getItem('kicc.theme')||'system';document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t}catch(e){document.documentElement.dataset.theme='light'}</script>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,200;0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400&family=Inter+Tight:wght@300;400;450;500&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/approved-design.css"><link rel="stylesheet" href="/css/rebuild.css"></head>
<body><a class="skip-link" href="#app">Skip to content</a>
<header class="nav rb-nav" id="nav"><div class="nav-inner"><a href="{{ route('home') }}" class="logo"><span class="mark">K</span><span>KICC<small>National Exhibition Platform</small></span></a><nav class="nav-links" aria-label="Public navigation"><a href="/counties">Counties</a><a href="/national-government">National Government</a><a href="/sectors">Sectors</a><a href="/products">Marketplace</a><a href="/venues">Venues</a><a href="/institutions">Institutions</a><a href="/exhibitions">Programme</a></nav><div class="nav-cta"><button class="theme-control" type="button" data-theme-control>Theme · Auto</button>@auth @if(auth()->user()->is_admin)<a class="btn ghost sm" href="{{ route('admin.index') }}">Admin</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button class="btn ghost sm" type="submit">Sign out</button></form>@else<a class="btn ghost sm" href="{{ route('login') }}">Sign in</a>@endauth<button class="burger" type="button" id="burger" aria-label="Open navigation" aria-expanded="false" aria-controls="mobileMenu">☰</button></div></div></header>
<div class="mobile-menu" id="mobileMenu" hidden><button type="button" class="btn ghost" data-menu-close>Close menu</button>@foreach(config('kicc.types') as $type=>$label)<a href="{{ route('directory',$type) }}">{{ $label }}</a>@endforeach<a href="/national-government">National Government Portal</a><a href="{{ route('login') }}">Sign in</a></div>
<main id="app" class="@yield('main-class')">@if(session('success'))<div class="wrap rb-notice" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="wrap rb-errors" role="alert"><strong>Changes were not saved.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main>
<footer class="footer rb-footer"><div class="wrap"><a href="/" class="logo"><span class="mark">K</span><span>KICC<small>National Exhibition Platform</small></span></a><p class="muted-xs" style="margin-top:25px">Africa's premier meeting venue and Kenya's national exhibition infrastructure. A national icon since 1973 — connecting all 47 counties on one video-native platform.</p><div class="rb-footer-links"><a href="/national-government">National Government Portal</a>@foreach(config('kicc.types') as $type=>$label)<a href="{{ route('directory',$type) }}">{{ $label }}</a>@endforeach</div><p class="muted-xs">© {{ date('Y') }} KICC · Imported reference content is identified by its source. Dates, capacities, prices and rosters require owner verification.</p></div></footer>
<script defer src="/js/rebuild.js"></script>@stack('scripts')</body></html>
