import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileBarChart, Download, Calendar, FileText, Check } from 'lucide-react';
import { mockReports, mockExports } from '../lib/mock-data';
import { cn, getStatusColor } from '../lib/utils';

export default function Reports() {
  const [exports, setExports] = useState(mockExports);
  const [generating, setGenerating] = useState<string | null>(null);

  const generate = (report: (typeof mockReports)[number]) => {
    setGenerating(report.id);
    setTimeout(() => {
      setExports((prev) => [
        {
          id: `EXP-${1043 + prev.length}`,
          name: `${report.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-aug-2026.pdf`,
          size: '1.2 MB',
          by: 'M. County Admin',
          date: 'Aug 24, 2026',
          status: 'active' as const,
          emoji: '📄',
        },
        ...prev,
      ]);
      setGenerating(null);
    }, 1200);
  };

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-black text-white">Reports & Exports</h1>
          <p className="text-sm text-text-muted">Scheduled reporting, on-demand exports and data delivery</p>
        </div>
        <span className="pill-badge badge-active flex items-center gap-1.5"><Calendar size={11} /> 4 schedules active</span>
      </motion.div>

      {/* Report Templates */}
      <div className="grid grid-cols-3 gap-4">
        {mockReports.map((report, i) => (
          <motion.div
            key={report.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
            className="glass-card glass-card-hover p-5 flex flex-col"
          >
            <div className="flex items-start justify-between mb-3">
              <div className="kpi-icon-wrap bg-violet/15"><FileBarChart size={16} className="text-violet" /></div>
              <span className="pill-badge bg-surface-light text-text-muted border border-border !text-[10px]">{report.schedule}</span>
            </div>
            <h4 className="text-sm font-bold text-white mb-1">{report.name}</h4>
            <p className="text-xs text-text-muted leading-relaxed flex-1 mb-3">{report.description}</p>
            <div className="flex items-center justify-between text-[10px] text-text-muted mb-3">
              <span>Format: {report.format}</span>
              <span>Last: {report.lastRun}</span>
            </div>
            <button
              onClick={() => generate(report)}
              disabled={generating === report.id}
              className={cn(
                'w-full py-2 rounded-lg text-xs font-semibold transition-all flex items-center justify-center gap-1.5',
                generating === report.id
                  ? 'bg-cyan/15 text-cyan border border-cyan/30 cursor-wait'
                  : 'btn-secondary hover:!border-violet/40'
              )}
            >
              {generating === report.id ? (
                <><span className="w-3 h-3 border-2 border-cyan/30 border-t-cyan rounded-full animate-spin" /> Generating...</>
              ) : (
                <><Download size={12} /> Generate Now</>
              )}
            </button>
          </motion.div>
        ))}
      </div>

      {/* Recent Exports */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-5">
        <h3 className="text-base font-bold text-white mb-1">Recent Exports</h3>
        <p className="text-xs text-text-muted mb-4">Generated files available for download · retained 90 days</p>
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-2.5 px-3 text-[11px] font-bold text-text-muted uppercase tracking-wider">File</th>
              <th className="text-left py-2.5 px-3 text-[11px] font-bold text-text-muted uppercase tracking-wider">Generated By</th>
              <th className="text-left py-2.5 px-3 text-[11px] font-bold text-text-muted uppercase tracking-wider">Date</th>
              <th className="text-right py-2.5 px-3 text-[11px] font-bold text-text-muted uppercase tracking-wider">Size</th>
              <th className="text-right py-2.5 px-3 text-[11px] font-bold text-text-muted uppercase tracking-wider">Action</th>
            </tr>
          </thead>
          <tbody>
            {exports.map((exp) => (
              <tr key={exp.id} className="border-b border-border/50 hover:bg-surface-hover/60 transition-colors group">
                <td className="py-3 px-3">
                  <div className="flex items-center gap-2.5">
                    <span className="text-lg">{exp.emoji}</span>
                    <div>
                      <div className="font-mono text-xs text-cyan">{exp.name}</div>
                      <div className="text-[10px] text-text-muted font-mono">{exp.id}</div>
                    </div>
                  </div>
                </td>
                <td className="py-3 px-3 text-text-secondary">{exp.by}</td>
                <td className="py-3 px-3 text-text-secondary">{exp.date}</td>
                <td className="py-3 px-3 text-right text-text-secondary">{exp.size}</td>
                <td className="py-3 px-3 text-right">
                  <button className="pill-badge bg-violet/15 text-violet border border-violet/30 hover:bg-violet hover:text-white transition-all">
                    <Download size={10} className="mr-1" /> Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </motion.div>
    </div>
  );
}
