const KICC = (() => {
const COUNTIES = [
  ["Baringo","Rift Valley",669000,["Tourism","Energy","Fisheries"],"030"],
  ["Bomet","Rift Valley",597000,["Tea","Dairy","Agriculture"],"036"],
  ["Bungoma","Western",1670000,["Agriculture","Education","Trade"],"047"],
  ["Busia","Western",893000,["Trade","Agriculture","Cross-Border Commerce"],"039"],
  ["Elgeyo-Marakwet","Rift Valley",454000,["Sports Tourism","Agriculture","Mining"],"028"],
  ["Embu","Eastern",608000,["Agriculture","Education","Technology"],"014"],
  ["Garissa","North Eastern",841000,["Pastoralism","Trade","Cross-Border Commerce"],"007"],
  ["Homa Bay","Nyanza",1131000,["Fisheries","Agriculture","Tourism"],"042"],
  ["Isiolo","Eastern",268000,["Pastoralism","Tourism","Trade"],"011"],
  ["Kajiado","Rift Valley",1119000,["Real Estate","Tourism","Mining"],"034"],
  ["Kakamega","Western",1890000,["Agriculture","Education","Healthcare"],"037"],
  ["Kericho","Rift Valley",901000,["Tea","Agriculture","Education"],"035"],
  ["Kiambu","Central",2417000,["Real Estate","Manufacturing","Agriculture"],"022"],
  ["Kilifi","Coast",1453000,["Tourism","Agriculture","Fisheries"],"003"],
  ["Kirinyaga","Central",640000,["Agriculture","Rice Farming","Education"],"020"],
  ["Kisii","Nyanza",1349000,["Agriculture","Education","Trade"],"044"],
  ["Kisumu","Nyanza",1155000,["Trade","Fisheries","Manufacturing"],"041"],
  ["Kitui","Eastern",1136000,["Agriculture","Mining","Solar Energy"],"015"],
  ["Kwale","Coast",866000,["Tourism","Mining","Agriculture"],"002"],
  ["Laikipia","Rift Valley",518000,["Tourism","Conservation","Agriculture"],"031"],
  ["Lamu","Coast",143000,["Tourism","Fisheries","Maritime Trade"],"005"],
  ["Machakos","Eastern",1421000,["Real Estate","Education","Agriculture"],"016"],
  ["Makueni","Eastern",987000,["Agriculture","Education","Fruit Processing"],"017"],
  ["Mandera","North Eastern",514000,["Pastoralism","Cross-Border Trade","Education"],"009"],
  ["Marsabit","Eastern",459000,["Pastoralism","Conservation","Renewable Energy"],"010"],
  ["Meru","Eastern",1529000,["Agriculture","Tourism","Education"],"012"],
  ["Migori","Nyanza",1175000,["Mining","Agriculture","Fisheries"],"043"],
  ["Mombasa","Coast",1260000,["Tourism","Transport","Trade"],"001"],
  ["Murang'a","Central",1086000,["Agriculture","Education","Tea Farming"],"021"],
  ["Nairobi City","Nairobi",5544000,["Technology","Finance","Manufacturing"],"046"],
  ["Nakuru","Rift Valley",2193000,["Tourism","Agriculture","Manufacturing"],"032"],
  ["Nandi","Rift Valley",885000,["Agriculture","Dairy","Tea"],"029"],
  ["Narok","Rift Valley",1157000,["Tourism","Agriculture","Mining"],"033"],
  ["Nyamira","Nyanza",670000,["Agriculture","Tea","Education"],"045"],
  ["Nyandarua","Central",638000,["Agriculture","Dairy","Tourism"],"018"],
  ["Nyeri","Central",759000,["Agriculture","Tourism","Education"],"019"],
  ["Samburu","Rift Valley",310000,["Tourism","Pastoralism","Conservation"],"025"],
  ["Siaya","Western",993000,["Fisheries","Agriculture","Education"],"040"],
  ["Taita-Taveta","Coast",381000,["Tourism","Mining","Agriculture"],"006"],
  ["Tana River","Coast",380000,["Agriculture","Pastoralism","Energy"],"004"],
  ["Tharaka-Nithi","Eastern",393000,["Agriculture","Education","Healthcare"],"013"],
  ["Trans Nzoia","Rift Valley",998000,["Agriculture","Dairy","Education"],"026"],
  ["Turkana","Rift Valley",1351000,["Energy","Fisheries","Pastoralism"],"023"],
  ["Uasin Gishu","Rift Valley",1162000,["Agriculture","Manufacturing","Education"],"027"],
  ["Vihiga","Western",554000,["Agriculture","Education","Healthcare"],"038"],
  ["Wajir","North Eastern",721000,["Pastoralism","Trade","Telecommunications"],"008"],
  ["West Pokot","Rift Valley",619000,["Agriculture","Mining","Tourism"],"024"],
].map(([name,region,pop,sectors,code])=>({name,region,pop,sectors,code,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),id:30000+parseInt(code,10)}));
const PRODUCTS = [
{name:"Kilifi Cashew Nuts (Raw)",cat:"Agriculture & Produce",price:950,county:"Kilifi",slug:"kilifi-cashew-nuts-raw"},
{name:"Mombasa Spice Blend (Pilau Masala)",cat:"Food & Beverage",price:450,county:"Mombasa",slug:"mombasa-spice-blend-pilau-masala"},
{name:"Kisii Soapstone Sculpture",cat:"Crafts & Artisan",price:1500,county:"Kisii",slug:"kisii-soapstone-sculpture"},
{name:"Maasai Beaded Necklace",cat:"Crafts & Artisan",price:1200,county:"Narok",slug:"maasai-beaded-necklace"},
{name:"Nyeri AA Coffee Beans",cat:"Agriculture & Produce",price:1400,county:"Nyeri",slug:"nyeri-aa-coffee-beans"},
{name:"Kericho Purple Tea",cat:"Agriculture & Produce",price:900,county:"Kericho",slug:"kericho-purple-tea"},
{name:"Kitui Wild Honey",cat:"Food & Beverage",price:650,county:"Kitui",slug:"kitui-wild-honey"},
{name:"Lamu Swahili Carved Door Frame",cat:"Home & Decor",price:18500,county:"Lamu",slug:"lamu-swahili-carved-door-frame"},
{name:"Turkana Woven Basket (Ekiongo)",cat:"Crafts & Artisan",price:1800,county:"Turkana",slug:"turkana-woven-basket-ekiongo"},
{name:"Maasai Shuka Blanket",cat:"Textiles & Apparel",price:900,county:"Kajiado",slug:"maasai-shuka-blanket"},
{name:"Lake Victoria Tilapia (Sun-Dried)",cat:"Food & Beverage",price:750,county:"Kisumu",slug:"lake-victoria-tilapia-sun-dried"},
{name:"Eldoret White Maize (Dry)",cat:"Agriculture & Produce",price:700,county:"Uasin Gishu",slug:"eldoret-white-maize-dry"},
{name:"Kakamega Banana Crisps",cat:"Food & Beverage",price:350,county:"Kakamega",slug:"kakamega-banana-crisps"},
{name:"Baringo Sisal Kiondo Bag",cat:"Crafts & Artisan",price:2200,county:"Baringo",slug:"baringo-sisal-kiondo-bag"},
{name:"Compost from Organic Waste",cat:"Agriculture & Produce",price:500,county:"Murang'a",slug:"gikono-landfill-recycling-centre-compost-from-organic-waste-muranga"},
{name:"Kakuzi Macadamia Oil",cat:"Food & Beverage",price:1200,county:"Murang'a",slug:"kakuzi-plc-kakuzi-macadamia-oil-muranga"},
{name:"Kakuzi Raw Macadamia Nuts",cat:"Food & Beverage",price:950,county:"Murang'a",slug:"kakuzi-plc-kakuzi-raw-macadamia-nuts-muranga"},
{name:"Kakuzi Roasted Macadamia Nuts",cat:"Food & Beverage",price:1100,county:"Murang'a",slug:"kakuzi-plc-kakuzi-roasted-macadamia-nuts-muranga"},
{name:"Kakuzi Fresh Avocados",cat:"Fresh Produce",price:180,county:"Murang'a",slug:"kakuzi-plc-kakuzi-fresh-avocados-muranga"},
{name:"Kakuzi Blueberries",cat:"Fresh Produce",price:850,county:"Murang'a",slug:"kakuzi-plc-kakuzi-blueberries-muranga"},
{name:"BREW IT Purple Tea",cat:"Food & Beverage",price:1500,county:"Murang'a",slug:"gatura-greens-brew-it-purple-tea-muranga"},
{name:"BREW IT Green Tea",cat:"Food & Beverage",price:1200,county:"Murang'a",slug:"gatura-greens-brew-it-green-tea-muranga"},
{name:"BREW IT Black Tea",cat:"Food & Beverage",price:1200,county:"Murang'a",slug:"gatura-greens-brew-it-black-tea-muranga"},
{name:"BREW IT Hibiscus Tea",cat:"Food & Beverage",price:1400,county:"Murang'a",slug:"gatura-greens-brew-it-hibiscus-tea-muranga"},
];
const VENUES = [
{name:"Tsavo Hall",type:"Plenary Hall",cap:2400,status:'Available',desc:''},
{name:"Amphitheatre",type:"Theatre",cap:700,status:'Available',desc:''},
{name:"Aberdares",type:"Meeting Room",cap:250,status:'Available',desc:''},
{name:"Lenana Hills",type:"Boardroom",cap:80,status:'Available',desc:''},
{name:"Shimba Hills",type:"Meeting Room",cap:120,status:'Available',desc:''},
{name:"Courtyard",type:"Outdoor",cap:500,status:'Available',desc:''},
{name:"Lawn",type:"Outdoor",cap:1000,status:'Available',desc:''},
{name:"Upper COMESA",type:"Meeting Room",cap:300,status:'Available',desc:''},
{name:"Lower COMESA",type:"Meeting Room",cap:200,status:'Available',desc:''},
{name:"Helipad",type:"VIP\/Events",cap:0,status:'Available',desc:''},
];
return {COUNTIES,PRODUCTS,VENUES,EXHIBITIONS:KICC.EXHIBITIONS||[],SCREENS:KICC.SCREENS||[],STREAMS:KICC.STREAMS||[],CONTENT:[]};
});
